# The "embed" package was introduced in Go 1.16.
runtime: go116

# app.yaml is supposed to be in the same directory as go.mod.
main: cmd/yambsd

# Try to limit costs.
automatic_scaling:
  max_instances: 1
  max_idle_instances: 1

handlers:
  - url: /(edits)?
    script: auto
    secure: always
