// This file is derived from https://github.com/metabrainz/musicbrainz-server,
// which is licensed under GNU General Public License (GPL) Version 2 or later.
// This license is located at COPYING-enums.md.

package seed

// This file was automatically generated from a copy of
// https://raw.githubusercontent.com/metabrainz/musicbrainz-server/master/t/sql/initial.sql
// downloaded at 2023-01-20 23:38:12 UTC.
// It can be regenerated by running "go generate".

// LinkType is an ID describing an attribute associated with a link between two
// MusicBrainz entities.
type LinkAttributeType int

const (
	// This attribute describes if a particular role was considered normal or
	// additional.
	LinkAttributeType_Additional LinkAttributeType = 1
	// This attribute describes if a particular collaboration was considered equal
	// or minor.
	LinkAttributeType_Minor LinkAttributeType = 2
	// This attribute describes a type of vocal performance.
	LinkAttributeType_Vocal LinkAttributeType = 3
	// Lead or solo vocal
	LinkAttributeType_LeadVocals LinkAttributeType = 4
	// choir vocals
	LinkAttributeType_ChoirVocals LinkAttributeType = 13
	// This attribute describes the possible instruments that can be captured as
	// part of a performance.
	// <br/>
	// Can't find an instrument? <a
	// href="http://wiki.musicbrainz.org/Advanced_Instrument_Tree">Request it!</a>
	LinkAttributeType_Instrument LinkAttributeType = 14
	LinkAttributeType_Horn       LinkAttributeType = 40
	LinkAttributeType_Trombone   LinkAttributeType = 46
	LinkAttributeType_Strings    LinkAttributeType = 69
	LinkAttributeType_Guitars    LinkAttributeType = 75
	LinkAttributeType_Violin     LinkAttributeType = 86
	LinkAttributeType_Lyre       LinkAttributeType = 109
	LinkAttributeType_Zither     LinkAttributeType = 123
	LinkAttributeType_Drums      LinkAttributeType = 125
	// This attribute indicates a 'guest' performance where the performer is not
	// usually part of the band.
	LinkAttributeType_Guest    LinkAttributeType = 194
	LinkAttributeType_Guitar   LinkAttributeType = 229
	LinkAttributeType_Keyboard LinkAttributeType = 232
	// Bass (modern, typically electrical, but not always)
	LinkAttributeType_BassGuitar               LinkAttributeType = 277
	LinkAttributeType_PluckedStringInstruments LinkAttributeType = 302
	LinkAttributeType_Tambourine               LinkAttributeType = 333
	// co-[role]
	LinkAttributeType_Co LinkAttributeType = 424
	// This attribute is to be used if the role was fulfilled in an executive
	// capacity.
	LinkAttributeType_Executive LinkAttributeType = 425
	// This attribute indicates a version with satirical, ironic, or otherwise
	// humorous intent. Parodies in most cases have altered lyrics.
	LinkAttributeType_Parody LinkAttributeType = 511
	// Indicates a bonus disc
	LinkAttributeType_Bonus LinkAttributeType = 516
	// This attribute indicates a version with the lyrics in a different language
	// than the original.
	LinkAttributeType_Translated LinkAttributeType = 517
	// This attribute indicates that an artist was a founding member of a group
	// artist.
	LinkAttributeType_Founder LinkAttributeType = 525
	// This typically indicates someone who is either a first-timer, or less
	// experienced, and who is working under the direction of someone who is more
	// experienced.
	LinkAttributeType_Assistant LinkAttributeType = 526
	// This typically indicates someone who is less experienced and who is working
	// under the direction of someone who is more experienced.
	LinkAttributeType_Associate LinkAttributeType = 527
	// Indicates that one entity is a cover of another entity
	LinkAttributeType_Cover   LinkAttributeType = 567
	LinkAttributeType_Medium  LinkAttributeType = 568
	LinkAttributeType_Medium2 LinkAttributeType = 569
	LinkAttributeType_Medium1 LinkAttributeType = 570
	LinkAttributeType_Medium3 LinkAttributeType = 571
	LinkAttributeType_Medium9 LinkAttributeType = 572
	LinkAttributeType_Medium8 LinkAttributeType = 573
	LinkAttributeType_Medium7 LinkAttributeType = 574
	LinkAttributeType_Medium6 LinkAttributeType = 575
	LinkAttributeType_Medium5 LinkAttributeType = 576
	LinkAttributeType_Medium4 LinkAttributeType = 577
	// This indicates that the recording is not of the entire work, e.g. excerpts
	// from, conclusion of, etc.
	LinkAttributeType_Partial LinkAttributeType = 579
	// This indicates that the recording is of a live performance.
	LinkAttributeType_Live LinkAttributeType = 578
	// For works that have lyrics, this indicates that those lyrics are not
	// relevant to this recording. Examples include instrumental arrangements, or
	// "beats" from hip-hop songs which may be reused with different lyrics.
	LinkAttributeType_Instrumental LinkAttributeType = 580
	// This attribute indicates that the streamable content is not audio but video.
	LinkAttributeType_Video LinkAttributeType = 582
	// This should be used when an artist is credited in liner notes or a similar
	// source as performing a solo part.
	LinkAttributeType_Solo LinkAttributeType = 596
	// This title indicates that a conductor has at least partially retired, and no
	// longer plays an active role with the group.
	LinkAttributeType_Emeritus LinkAttributeType = 617
	// This indicates that the group had multiple conductors who were led by this
	// conductor. This may be indicated by either the title of "principal
	// conductor" or "first conductor".
	LinkAttributeType_Principal LinkAttributeType = 618
	// variously sized drums
	LinkAttributeType_OtherDrums LinkAttributeType = 700
	// This indicates that the recording is of a medley, of which the work is one
	// part.
	LinkAttributeType_Medley LinkAttributeType = 750
	// This attribute indicates the number of a work in a series.
	LinkAttributeType_Number LinkAttributeType = 788
	// Local time a band's performance is scheduled to start, formatted HH:MM.
	LinkAttributeType_Time LinkAttributeType = 830
)

// LinkType is an ID describing a link between two MusicBrainz entities.
// It sadly doesn't appear to enumerate all possible values. There are 170-ish
// additional link types with translations in po/relationships.pot, many of
// which don't appear to be referenced anywhere else in the server repo.
type LinkType int

const (
	// This is used to link an artist to its corresponding page on Allmusic.
	LinkType_AllMusic_Artist_URL LinkType = 283
	// This is used to link a genre to its corresponding page on Allmusic.
	LinkType_AllMusic_Genre_URL LinkType = 1093
	// This is used to link a recording to its corresponding page on Allmusic.
	LinkType_AllMusic_Recording_URL LinkType = 285
	// This is used to link a release group to its corresponding page on Allmusic.
	LinkType_AllMusic_ReleaseGroup_URL LinkType = 284
	// This is used to link a release to its corresponding page on Allmusic.
	LinkType_AllMusic_Release_URL LinkType = 755
	// This is used to link a work to its corresponding page on Allmusic.
	LinkType_AllMusic_URL_Work LinkType = 286
	// This links a MusicBrainz release to the equivalent entry at Amazon and will
	// often provide cover art if there is no cover art in the <a
	// href="/doc/Cover_Art_Archive">Cover Art Archive</a>.
	LinkType_AmazonASIN_Release_URL LinkType = 77
	// Designates that a work is or was the anthem for an area
	LinkType_Anthem_Area_Work LinkType = 357
	// Links a recording to the place it was arranged at.
	LinkType_ArrangedAt_Place_Recording LinkType = 866
	// Links a release to the place it was arranged at.
	LinkType_ArrangedAt_Place_Release LinkType = 865
	// Links a recording to the area it was arranged in. Use only when the place is
	// unknown!
	LinkType_ArrangedIn_Area_Recording LinkType = 864
	// Links a release to the area it was arranged in. Use only when the place is
	// unknown!
	LinkType_ArrangedIn_Area_Release LinkType = 863
	// This links two <a href="/doc/Work" title="Work">works</a> where one work is
	// an arrangement of the other.
	LinkType_Arrangement_Work_Work LinkType = 350
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_Arranger_Artist_Recording LinkType = 297
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_Arranger_Artist_Release LinkType = 295
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_Arranger_Artist_Work LinkType = 293
	// This indicates that a person or agency did the art direction for the
	// recording.
	LinkType_ArtDirection_Artist_Recording LinkType = 137
	// This indicates that a person or agency did the art direction for the
	// release.
	LinkType_ArtDirection_Artist_Release LinkType = 18
	// This indicates a person or agency which is responsible for talent scouting,
	// overseeing the artistic development of an artist, and acting as liaison
	// between artists and the labels.
	LinkType_ArtistsAndRepertoire_Artist_Recording LinkType = 135
	// This indicates a person or agency which is responsible for talent scouting,
	// overseeing the artistic development of an artist, and acting as liaison
	// between artists and the labels.
	LinkType_ArtistsAndRepertoire_Artist_ReleaseGroup LinkType = 62
	// This relationship type links instruments to genres they are commonly used
	// in.
	LinkType_AssociatedInstrument_Genre_Instrument LinkType = 1090
	// This describes an engineer involved with the machines used to generate
	// sound, such as effects processors and digital audio equipment used to modify
	// or manipulate sound in either an analogue or digital form.
	LinkType_Audio_Artist_Recording LinkType = 140
	// This describes an engineer involved with the machines used to generate
	// sound, such as effects processors and digital audio equipment used to modify
	// or manipulate sound in either an analogue or digital form.
	LinkType_Audio_Artist_Release LinkType = 31
	// Links a release with an event where it was available. This is intended for
	// event-exclusive releases and/or releases available at events before the
	// official launch date, not for every release in the merchandise stall.
	LinkType_AvailableAt_Event_Release LinkType = 795
	// This links a recording to the balance engineer who engineered it.
	LinkType_Balance_Artist_Recording LinkType = 726
	// This links a release to the balance engineer who engineered it.
	LinkType_Balance_Artist_Release LinkType = 727
	// This links an artist to its page at Bandcamp.
	LinkType_Bandcamp_Artist_URL LinkType = 718
	// This links a genre to its page at Bandcamp.
	LinkType_Bandcamp_Genre_URL LinkType = 1092
	// This links a label to its page at Bandcamp.
	LinkType_Bandcamp_Label_URL LinkType = 719
	// This relationship type links an artist to its corresponding page at
	// Bandsintown.
	LinkType_Bandsintown_Artist_URL LinkType = 862
	// This relationship type links an event to its corresponding page at
	// Bandsintown.
	LinkType_Bandsintown_Event_URL LinkType = 860
	// This relationship type links a place to its corresponding page at
	// Bandsintown.
	LinkType_Bandsintown_Place_URL LinkType = 861
	// This links two <a href="/doc/Work" title="Work">works</a>, where the second
	// work is based on music or text from the first, but isn't directly a revision
	// or an arrangement of it.
	LinkType_BasedOn_Work_Work LinkType = 314
	// This links an artist to that artist's page at <a
	// href="https://www.bbc.co.uk/music">BBC Music</a>.
	LinkType_BbcMusicPage_Artist_URL LinkType = 190
	// This links an artist to an online biography for that artist.
	LinkType_Biography_Artist_URL LinkType = 182
	// This relationship type is used to link an artist to their blog.
	LinkType_Blog_Artist_URL LinkType = 199
	// This relationship type is used to link a label to its blog.
	LinkType_Blog_Label_URL LinkType = 224
	// This relationship type can be used to link a place to its blog
	LinkType_Blog_Place_URL LinkType = 627
	// Points to the BookBrainz page for this artist.
	LinkType_BookBrainz_Artist_URL LinkType = 852
	// Points to the BookBrainz page for this label.
	LinkType_BookBrainz_Label_URL LinkType = 851
	// Points to the BookBrainz page for this release group.
	LinkType_BookBrainz_ReleaseGroup_URL LinkType = 853
	// Points to the BookBrainz page for this release.
	LinkType_BookBrainz_Release_URL LinkType = 850
	// Points to the BookBrainz page for this work.
	LinkType_BookBrainz_URL_Work LinkType = 854
	// This credits a person who was responsible for booking the studio or
	// performance venue where the recording was recorded.
	LinkType_Booking_Artist_Recording LinkType = 134
	// This credits a person who was responsible for booking the studio or
	// performance venue where the release was recorded.
	LinkType_Booking_Artist_Release          LinkType = 23
	LinkType_BusinessAssociation_Label_Label LinkType = 205
	// This links to a catalog or list of records published by the label.
	LinkType_CatalogSite_Label_URL LinkType = 212
	// This relationship is used to link a catalogue work series to a person who
	// was involved in compiling it.
	LinkType_Catalogued_Artist_Series       LinkType = 751
	LinkType_Children_Instrument_Instrument LinkType = 735
	// This indicates the chorus master of a choir which performed on this
	// recording.
	LinkType_ChorusMaster_Artist_Recording LinkType = 152
	// This indicates the chorus master of a choir which performed on this release.
	LinkType_ChorusMaster_Artist_Release LinkType = 53
	// This is used to specify that an <a href="/doc/Artist"
	// title="Artist">artist</a> collaborated on a short-term project, for cases
	// where artist credits can't be used.
	LinkType_Collaboration_Artist_Artist LinkType = 102
	// This indicates that a recording is a compilation of several other
	// recordings. This applies to one long recording that contains multiple songs,
	// one after the other, in which the audio material of the original recordings
	// has not been altered. If the tracks are pitched or blended into each other,
	// the <a href="/relationship/451076df-61cf-46ab-9921-555cab2f050d">DJ-mix
	// relationship type</a> may be more appropriate.
	LinkType_Compilation_Recording_Recording LinkType = 228
	// This indicates the person who selected the tracks and the sequence for a
	// compilation. This applies to one long recording which contains multiple
	// songs, one after the other. If the tracks are pitched or blended into each
	// other, it is more appropriate to credit this person as a <a
	// href="/relationship/28338ee6-d578-485a-bb53-61dbfd7c6545">DJ-mixer</a>.
	LinkType_Compiler_Artist_Recording LinkType = 147
	// This indicates the person who selected the tracks and the sequence for a
	// compilation. If the tracks are pitched or blended into each other, it is
	// more appropriate to credit this person as a <a
	// href="/relationship/9162dedd-790c-446c-838e-240f877dbfe2">DJ-mixer</a>.
	LinkType_Compiler_Artist_Release LinkType = 48
	// This links a group (often an orchestra) to a composer who has a
	// composer-in-residence position with the group.
	LinkType_ComposerInResidence_Artist_Artist LinkType = 855
	// Indicates the composer for this release, i.e. the artist who wrote the music
	// (not necessarily the lyrics).
	LinkType_Composer_Artist_Release LinkType = 55
	// Indicates the composer for this work, i.e. the artist who wrote the music
	// (not necessarily the lyrics).
	LinkType_Composer_Artist_Work       LinkType = 168
	LinkType_Composition_Artist_Release LinkType = 58
	LinkType_Composition_Artist_Work    LinkType = 170
	// This indicates an artist who was the concertmaster/leader for an orchestra
	// or band on this recording.
	LinkType_Concertmaster_Artist_Recording LinkType = 760
	// This indicates an artist who was the concertmaster/leader for an orchestra
	// or band on this release.
	LinkType_Concertmaster_Artist_Release LinkType = 759
	// This indicates that a person is, or was, a conductor for a group.
	LinkType_ConductorPosition_Artist_Artist LinkType = 305
	// Links an event to an artist that was a conductor in it.
	LinkType_Conductor_Artist_Event LinkType = 806
	// This indicates an artist who conducted an orchestra, band or choir on this
	// recording.
	LinkType_Conductor_Artist_Recording LinkType = 151
	// This indicates an artist who conducted an orchestra, band or choir on this
	// release.
	LinkType_Conductor_Artist_Release LinkType = 46
	LinkType_Contract_Artist_Label    LinkType = 119
	// This relationship indicates the artist is the copyright holder for this
	// release.
	LinkType_Copyright_Artist_Release LinkType = 709
	// This relationship indicates the label is the copyright holder for this
	// release.
	LinkType_Copyright_Label_Release LinkType = 708
	// This relationship type is <strong>deprecated</strong>! Please upload covers
	// on the cover art tab for the release and/or add an ASIN
	// relationship.\n\nNote about CD Baby: Many CD Baby releases are also
	// available (usually with bigger covers) on Amazon.com.
	LinkType_CoverArtLink_Release_URL LinkType = 78
	// This relationship type is used to indicate that a release group is a cover
	// version of another release group, i.e. when an artist performs a new
	// rendition of another artist's album.<br/>
	// For individual songs, see the <a
	// href="/relationship/a3005666-a872-32c3-ad06-98af558e99b0">recording-work
	// performance relationship type</a>.
	LinkType_Cover_ReleaseGroup_ReleaseGroup             LinkType = 15
	LinkType_CoversAndVersions_Recording_Recording       LinkType = 233
	LinkType_CoversAndVersions_ReleaseGroup_ReleaseGroup LinkType = 12
	LinkType_CoversAndVersions_Release_Release           LinkType = 4
	// This credits a person or agency who provided some kind of general creative
	// inspiration during the recording of this recording, without actually
	// contributing to the writing or performance.
	LinkType_CreativeDirection_Artist_Recording LinkType = 146
	// This credits a person or agency who provided some kind of general creative
	// inspiration during the recording of this release group, without actually
	// contributing to the writing or performance.
	LinkType_CreativeDirection_Artist_ReleaseGroup LinkType = 63
	// This indicates that an artist was officially employed by a label in a
	// creative position, such as photographer or graphic designer.
	LinkType_CreativePosition_Artist_Label LinkType = 115
	// This links a recording to the relevant crowdfunding project at a
	// crowdfunding site like Kickstarter or Indiegogo.
	LinkType_Crowdfunding_Recording_URL LinkType = 905
	// This links a release to the relevant crowdfunding project at a crowdfunding
	// site like Kickstarter or Indiegogo.
	LinkType_Crowdfunding_Release_URL LinkType = 906
	// This is used to link a <a href="/doc/Mix_Terminology#DJ_mix">DJ-mixed</a>
	// recording to each of the source recordings. See <a
	// href="/relationship/28338ee6-d578-485a-bb53-61dbfd7c6545">DJ-mixer</a> for
	// crediting the person who created the DJ-mix.
	LinkType_DJMix_Recording_Recording LinkType = 227
	// This is used to link a release group containing a <a
	// href="/doc/Mix_Terminology#DJ_mix">DJ-mixed</a> version of a release to the
	// release group containing the source release. See <a
	// href="/relationship/9162dedd-790c-446c-838e-240f877dbfe2">DJ-mixer</a> for
	// crediting the person who created the DJ-mix.
	LinkType_DJMix_ReleaseGroup_ReleaseGroup LinkType = 8
	// This links a release group to an artist it is dedicated to. This is for
	// dedications such as "This album is dedicated to the memory of Artist" - for
	// tribute albums consisting of covers of the artist, use the <a
	// href="/relationship/5e2907db-49ec-4a48-9f11-dfb99d2603ff">tribute
	// relationship</a>.
	LinkType_DedicatedTo_Artist_ReleaseGroup LinkType = 868
	// This indicates the work is dedicated to a specific person. This is most
	// common for classical works, but also exists in other genres to a degree.
	LinkType_Dedication_Artist_Work LinkType = 846
	// derived from
	LinkType_Derivation_Instrument_Instrument LinkType = 737
	// This indicates a person or agency who did design or illustration for the
	// track.
	LinkType_DesignIllustration_Artist_Recording LinkType = 130
	// This indicates a person or agency who did design or illustration for the
	// release.
	LinkType_DesignIllustration_Artist_Release LinkType = 19
	// This link points to a page for a particular release within a discography for
	// an artist or label.
	LinkType_DiscographyEntry_Release_URL LinkType = 288
	// This links an artist to an online discography of their works. The
	// discography should provide a summary of most, if not all, releases by the
	// artist, and be as comprehensive as possible.
	LinkType_DiscographyPage_Artist_URL   LinkType = 184
	LinkType_Discography_Artist_URL       LinkType = 171
	LinkType_Discography_ReleaseGroup_URL LinkType = 88
	// This is used to link the Discogs page for this artist.
	LinkType_Discogs_Artist_URL LinkType = 180
	// This is used to link the Discogs page for this genre/style.
	LinkType_Discogs_Genre_URL LinkType = 1089
	// This is used to link the Discogs page for this label.
	LinkType_Discogs_Label_URL LinkType = 217
	// This is used to link a place to the equivalent entry in Discogs.
	LinkType_Discogs_Place_URL LinkType = 705
	// This is used to link the Discogs page for this release group.
	LinkType_Discogs_ReleaseGroup_URL LinkType = 90
	// This is used to link the Discogs page for this release.
	LinkType_Discogs_Release_URL LinkType = 76
	// This is used to link a series to the equivalent entry in Discogs.
	LinkType_Discogs_Series_URL LinkType = 747
	// This indicates the organization that distributes (or contracts out
	// distribution).
	// This is <strong>not</strong> the same concept as the <a
	// href="/doc/Label">record label</a>.
	LinkType_Distributed_Label_Release LinkType = 361
	// Indicates a webpage where you can download an artist's work for free.
	LinkType_DownloadForFree_Artist_URL LinkType = 177
	// This links a recording to a page where it can be legally downloaded for
	// free.
	LinkType_DownloadForFree_Recording_URL LinkType = 255
	// This links a release to a page where it can be legally downloaded for free.
	LinkType_DownloadForFree_Release_URL LinkType = 75
	// This links an edit to its original recording. An "edit", for this
	// relationship, can be a radio edit (which involves streamlining a longer
	// track to around the 3 minute mark in order to make it suitable for radio
	// play), or a shortened, censored, or otherwise edited version of the same
	// material. The person who edited the recording can be linked using the <a
	// href="/relationship/40dff87a-e475-4aa6-b615-9935b564d756">editor
	// relationship type</a>.
	LinkType_Edit_Recording_Recording LinkType = 309
	// Links a recording to the place it was edited at.
	LinkType_EditedAt_Place_Recording LinkType = 819
	// Links a release to the place it was edited at.
	LinkType_EditedAt_Place_Release LinkType = 820
	// Links a recording to the area it was edited in. Use only when the place is
	// unknown!
	LinkType_EditedIn_Area_Recording LinkType = 821
	// Links a release to the area it was edited in. Use only when the place is
	// unknown!
	LinkType_EditedIn_Area_Release LinkType = 822
	// This describes an engineer responsible for either connecting disparate
	// elements of the audio recording, or otherwise redistributing material
	// recorded in the sessions. This is usually secondary, or additional to the
	// work done by the mix engineer. It can also involve streamlining a longer
	// track to around the 3 minute mark in order to make it suitable for radio
	// play (a "radio edit").
	LinkType_Editor_Artist_Recording LinkType = 144
	// This describes an engineer responsible for either connecting disparate
	// elements of the audio recording, or otherwise redistributing material
	// recorded in the sessions. This is usually secondary, or additional to the
	// work done by the mix engineer. It can also involve streamlining a longer
	// track to around the 3 minute mark in order to make it suitable for radio
	// play (a "radio edit").
	LinkType_Editor_Artist_Release LinkType = 38
	// This indicates that an artist was officially employed by a label as an
	// engineer.
	LinkType_EngineerPosition_Artist_Label LinkType = 120
	// Describes the fact a person was contracted by a place as an engineer.
	LinkType_EngineerPosition_Artist_Place LinkType = 701
	// This describes an engineer who performed a general engineering role.
	LinkType_Engineer_Artist_Recording LinkType = 138
	// This describes an engineer who performed a general engineering role.
	LinkType_Engineer_Artist_Release LinkType = 28
	// Links a recording to the place it was engineered at.
	LinkType_EngineeredAt_Place_Recording LinkType = 813
	// Links a release to the place it was engineered at.
	LinkType_EngineeredAt_Place_Release LinkType = 812
	// Links a recording to the area it was engineered in. Use only when the place
	// is unknown!
	LinkType_EngineeredIn_Area_Recording LinkType = 814
	// Links a release to the area it was engineered in. Use only when the place is
	// unknown!
	LinkType_EngineeredIn_Area_Release LinkType = 815
	// This links an artist to a fan-created website.
	LinkType_Fanpage_Artist_URL LinkType = 172
	// This links a label to a fan-created website.
	LinkType_Fanpage_Label_URL LinkType = 214
	// This relationship type is <strong>deprecated</strong>! If two recordings are
	// identical, please merge them.
	LinkType_FirstTrackRelease_Recording_Recording LinkType = 238
	// This relationship type can be used to link a place (generally a studio or
	// venue) to the person(s) who founded it.
	LinkType_Founder_Artist_Place LinkType = 832
	// This relationship type links genres to the areas they originate from.
	LinkType_GenreOrigin_Area_Genre LinkType = 1088
	// Points to the Geonames page for this area.
	LinkType_Geonames_Area_URL         LinkType = 713
	LinkType_GetTheMusic_Artist_URL    LinkType = 187
	LinkType_GetTheMusic_Genre_URL     LinkType = 1091
	LinkType_GetTheMusic_Recording_URL LinkType = 257
	LinkType_GetTheMusic_Release_URL   LinkType = 73
	// This credits the people or agency who did the graphic design, arranging
	// pieces of content into a coherent and aesthetically-pleasing sleeve design.
	LinkType_GraphicDesign_Artist_Recording LinkType = 125
	// This credits the people or agency who did the graphic design, arranging
	// pieces of content into a coherent and aesthetically-pleasing sleeve design.
	LinkType_GraphicDesign_Artist_Release LinkType = 27
	// Links an event to a guest performer. Guest performers usually make short
	// appearances during other artist's set.
	LinkType_GuestPerformer_Artist_Event LinkType = 800
	// This relationship is used to link a catalogue work series to a person whose
	// work it catalogues.
	LinkType_HasCatalogue_Artist_Series LinkType = 750
	// Links an event to the place where it was held.
	LinkType_HeldAt_Event_Place LinkType = 794
	// Links an event to the area where it was held. Use only if the exact place is
	// unknown.
	LinkType_HeldIn_Area_Event LinkType = 793
	// This links to a site describing relevant details about a label's history.
	LinkType_HistorySite_Label_URL LinkType = 211
	// Links an event to its host/MC. Event hosts usually do introductions to the
	// show or each song.
	LinkType_Host_Artist_Event LinkType = 801
	// This relationship type describes that the recording contains samples taken
	// from a movie, show or game, which has an IMDB page at the given URL.
	// <br/><br/>
	// To say that the recording is part of a soundtrack, please use the <a
	// href="/relationship/85b0a010-3237-47c7-8476-6fcefd4761af">IMDB relationship
	// type for release groups</a>.
	LinkType_IMDBSamples_Recording_URL LinkType = 258
	// This relationship is deprecated, since it's almost always misused. To
	// specify that a recording on this release contains samples taken from a
	// movie, show or game, use the recording - URL relationship. If you don't know
	// what recording(s) use the samples, please just indicate it in the
	// annotation.
	// <br/><br/>
	// To say that the release is a soundtrack, please use the <a
	// href="/relationship/85b0a010-3237-47c7-8476-6fcefd4761af">IMDB relationship
	// type for release groups</a>.
	LinkType_IMDBSamples_Release_URL LinkType = 83
	// This links an artist to its page in <a
	// href="https://www.imdb.com/">IMDb</a>.
	LinkType_IMDB_Artist_URL LinkType = 178
	// This links a label to its page in <a href="https://www.imdb.com/">IMDb</a>.
	LinkType_IMDB_Label_URL LinkType = 313
	// Points to the Internet Movie Database page for this place.
	LinkType_IMDB_Place_URL LinkType = 706
	// This links a soundtrack release to the <a
	// href="https://www.imdb.com/">IMDb</a> page for the movie, show or game of
	// which it is a soundtrack.
	LinkType_IMDB_ReleaseGroup_URL LinkType = 97
	// This links a soundtrack work to the <a href="https://www.imdb.com/">IMDb</a>
	// page for the movie, show or game of which it is a soundtrack.
	LinkType_IMDB_URL_Work LinkType = 843
	// This links an artist to its page in <a
	// href="http://www.imslp.org/">IMSLP</a>.
	LinkType_IMSLP_Artist_URL LinkType = 754
	// Indicates a pictorial image (JPEG, GIF, PNG) of an artist.
	LinkType_Image_Artist_URL LinkType = 173
	// image
	LinkType_Image_Instrument_URL LinkType = 732
	// Indicates a pictorial image (JPEG, GIF, PNG) of a place
	LinkType_Image_Place_URL LinkType = 396
	// This indicates that a record label (company) owns or has the right to use an
	// imprint.
	LinkType_Imprint_Label_Label LinkType = 725
	// information page
	LinkType_InformationPage_Instrument_URL LinkType = 734
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_InstrumentArranger_Artist_Recording LinkType = 158
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_InstrumentArranger_Artist_Release LinkType = 41
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_InstrumentArranger_Artist_Work LinkType = 282
	// This relationship type links instruments to the areas they originate from.
	LinkType_InstrumentOrigin_Area_Instrument LinkType = 752
	// Indicates an artist that performed one or more instruments on this
	// recording.
	LinkType_Instrument_Artist_Recording LinkType = 148
	// Indicates an artist that performed one or more instruments on this release.
	LinkType_Instrument_Artist_Release LinkType = 44
	// Indicates a musician doing long-time instrumental support for another one on
	// albums and/or at concerts. This is a person-to-artist relationship that
	// normally applies to well-known solo artists, although it can sometimes apply
	// to groups.
	LinkType_InstrumentalSupportingMusician_Artist_Artist LinkType = 105
	// This links an artist to an URL containing an interview with that artist.
	LinkType_Interview_Artist_URL LinkType = 707
	// Indicates that two persons were romantically involved with each other
	// without being married.
	LinkType_InvolvedWith_Artist_Artist LinkType = 112
	// This links an artist's performance name (a stage name or alias) with their
	// legal name.
	LinkType_IsPerson_Artist_Artist LinkType = 108
	// This is used to link a karaoke version of a song to the original
	// song.<br/><br/>
	// A karaoke version is a version of the song with the main vocals removed,
	// designed to be used for karaoke. These are generally produced from the
	// original masters by muting the main vocal track or by using post-processing
	// filters to remove the vocals. Karaoke versions can be found labelled in
	// numerous different ways other than "karaoke": instrumental (even if backing
	// vocals are still present), off vocal, backing track, etc.
	LinkType_Karaoke_Recording_Recording LinkType = 226
	// This describes a situation where one label is distributing (part of) another
	// label's catalog, in a country/region of the world, during a period of time.
	LinkType_LabelDistribution_Label_Label LinkType = 203
	// This relationship type can be used to link a label to the person(s) who
	// founded it.
	LinkType_LabelFounder_Artist_Label LinkType = 116
	// This describes a situation where one label is (or was) a subsidiary of
	// another label, during a given period of time. This should be used either to
	// describe the fact a label is a subdivision of another one, or, through
	// corporate acquisition of the former label, has become a subdivision of
	// another one.
	LinkType_LabelOwnership_Label_Label LinkType = 200
	// This describes a situation where one label is reissuing, under its own name,
	// (part of) another label's catalog. This can happen in at least three cases:
	// <ul>
	// <li>A label acquires a lease on another label's catalog, for a period of
	// time, in a specific region of the world.</li>
	// <li>A label buys the rights to a defunct label's catalog, or buys a label
	// (with its catalog) and dismantles it.</li>
	// <li>A bootleg label reissues another label's catalog.</li>
	// </ul>
	LinkType_LabelReissue_Label_Label LinkType = 201
	// This describes a situation where a label has changed its name, either for
	// purely aesthetic reasons or following a buyout/sellout/spin-off. Extra care
	// should be taken with cases where complicated merge/split/restructure
	// financial operations are done. For example, it's not a good idea to rename
	// the label <a href="/label/99a24d71-54c1-4d3f-88cc-00fbcc4fce83">Verve</a>
	// into <a href="/label/4fb00dfd-7674-44c0-bf67-79daf8c61767">The Verve Music
	// Group</a>, as Verve continued its existence thereafter as an imprint.
	LinkType_LabelRename_Label_Label LinkType = 202
	// This relationship type links an artist to its corresponding page at Last.fm
	LinkType_Lastfm_Artist_URL LinkType = 840
	// This relationship type links an event to its corresponding page at Last.fm
	LinkType_Lastfm_Event_URL LinkType = 839
	// This relationship type links a label to its corresponding page at Last.fm
	LinkType_Lastfm_Label_URL LinkType = 838
	// This relationship type links a place to its corresponding page at Last.fm
	LinkType_Lastfm_Place_URL LinkType = 837
	// Links a release with a launch event for it.
	LinkType_LaunchEvent_Event_Release LinkType = 796
	// Links a release group with a launch event for it.
	LinkType_LaunchEvent_Event_ReleaseGroup LinkType = 797
	// This indicates that a person or firm provided legal representation for the
	// recording.
	LinkType_LegalRepresentation_Artist_Recording LinkType = 142
	// This indicates that a person or firm provided legal representation for the
	// release.
	LinkType_LegalRepresentation_Artist_Release LinkType = 22
	// Indicates the librettist for this release.
	LinkType_Librettist_Artist_Release LinkType = 57
	// Indicates the librettist for this work.
	LinkType_Librettist_Artist_Work LinkType = 169
	// This links a recording to a license under which it is available.
	LinkType_License_Recording_URL LinkType = 302
	// This links a release to a license under which it is available.
	LinkType_License_Release_URL LinkType = 301
	// This relationship indicates the company that was the licensee of this
	// release (that is, received a license for it from other company).
	LinkType_Licensee_Label_Release LinkType = 833
	// This relationship indicates the company that was the licensor of this
	// release.
	LinkType_Licensor_Label_Release LinkType = 712
	// This credits the author of liner notes provided with the release (usually on
	// the sleeve). While most time liner notes are just personnel information and
	// production data, in some cases they consist of a blurb of text (article).
	// This relationship type should be used in this last case.
	LinkType_LinerNotes_Artist_Release LinkType = 24
	// This is used to indicate that a release group is a live performance of a
	// studio release group.
	LinkType_LivePerformance_ReleaseGroup_ReleaseGroup LinkType = 17
	// This is used to link a label to an image of its logo.
	LinkType_Logo_Label_URL LinkType = 213
	// Indicates the lyricist for this release.
	LinkType_Lyricist_Artist_Release LinkType = 56
	// Indicates the lyricist for this work.
	LinkType_Lyricist_Artist_Work LinkType = 165
	// This relationship describes a URL where lyrics for the artist can be found.
	// Only sites on the <a
	// href="/doc/Style/Relationships/URLs/Lyrics_whitelist">whitelist</a> are
	// permitted.
	LinkType_Lyrics_Artist_URL LinkType = 197
	// This relationship describes a URL where lyrics for the release group can be
	// found. Only sites on the <a
	// href="/doc/Style/Relationships/URLs/Lyrics_whitelist">whitelist</a> are
	// permitted.
	LinkType_Lyrics_ReleaseGroup_URL LinkType = 93
	// This relationship describes a URL where lyrics for the work can be found.
	// Only sites on the <a
	// href="/doc/Style/Relationships/URLs/Lyrics_whitelist">whitelist</a> are
	// permitted.
	LinkType_Lyrics_URL_Work LinkType = 271
	// Links an event to (one of) its main performer(s).
	LinkType_MainPerformer_Artist_Event LinkType = 798
	// Links a release to the area it was manufactured ("made") in.
	LinkType_ManufacturedIn_Area_Release LinkType = 835
	// This indicates the organization that manufactures (or contracts out
	// manufacturing).
	// This is <strong>not</strong> the same concept as the <a
	// href="/doc/Label">record label</a>.
	LinkType_Manufactured_Label_Release LinkType = 360
	// This indicates the organization that markets a release. This is
	// <strong>not</strong> the same concept as the <a href="/doc/Label">record
	// label</a>.
	LinkType_Marketed_Label_Release LinkType = 848
	// This links artists who were married.
	LinkType_Married_Artist_Artist LinkType = 111
	// This is used to indicate that the recording is a <a
	// href="/doc/Mix_Terminology#mash-up">mash-up</a> of two (or more) other
	// recordings.
	LinkType_MashesUp_Recording_Recording LinkType = 232
	// This is used to indicate that the release group is a mash-up <a
	// href="/doc/Mix_Terminology#mash-up">mash-up</a> of two (or more) other
	// release groups.
	LinkType_MashesUp_ReleaseGroup_ReleaseGroup LinkType = 10
	// Links a release to the place it was mastered at.
	LinkType_MasteredAt_Place_Release LinkType = 697
	// Links a release to the area it was mastered in. Use only when the place is
	// unknown!
	LinkType_MasteredIn_Area_Release LinkType = 756
	// Describes the fact a person was contracted by a place as a mastering
	// engineer.
	LinkType_MasteringEngineerPosition_Artist_Place LinkType = 704
	// This relationship type is <strong>deprecated</strong>! Please add mastering
	// engineers at the release level.
	LinkType_Mastering_Artist_Recording LinkType = 136
	// Indicates the mastering engineer for this work.
	LinkType_Mastering_Artist_Release LinkType = 42
	// This is used to indicate that a work is a medley of several other songs.
	// This means that the original songs were rearranged to create a new work in
	// the form of a medley. See <a
	// href="/relationship/d3fd781c-5894-47e2-8c12-86cc0e2c8d08">arranger</a> for
	// crediting the person who arranges songs into a medley.
	LinkType_Medley_Work_Work LinkType = 239
	// This indicates a person is a member of a group.
	LinkType_MemberOfBand_Artist_Artist LinkType = 103
	// This indicates that the artist performed a role not covered by other
	// relationship types.
	LinkType_Misc_Artist_Recording LinkType = 129
	// This indicates that the artist performed a role not covered by other
	// relationship types.
	LinkType_Misc_Artist_Release LinkType = 25
	// Indicates a miscellaneous support role. This is usually stated in the liner
	// notes of an album.
	LinkType_Misc_Artist_Work LinkType = 162
	// This relationship type is <strong>deprecated</strong>.
	LinkType_Misc_URL_Work LinkType = 270
	// This links a <a href="/doc/Mix_Terminology#DJ_mix">DJ-mix</a> to the artist
	// who mixed it.
	LinkType_MixDJ_Artist_Recording LinkType = 155
	// This links a <a href="/doc/Mix_Terminology#DJ_mix">DJ-mix</a> to the artist
	// who mixed it.
	LinkType_MixDJ_Artist_Release LinkType = 43
	// This describes an engineer responsible for using a mixing console to mix a
	// recorded track into a single piece of music suitable for release. For
	// remixing, see <a
	// href="/relationship/7950be4d-13a3-48e7-906b-5af562e39544">remixer</a>.
	LinkType_Mix_Artist_Recording LinkType = 143
	// This describes an engineer responsible for using a mixing console to mix a
	// recorded track into a single piece of music suitable for release. For
	// remixing, see <a
	// href="/relationship/ac6a86db-f757-4815-a07e-744428d2382b">remixer</a>.
	LinkType_Mix_Artist_Release LinkType = 26
	// Links a recording to the place it was mixed at.
	LinkType_MixedAt_Place_Recording LinkType = 694
	// Links a release to the place it was mixed at.
	LinkType_MixedAt_Place_Release LinkType = 696
	// Links a recording to the area it was mixed in. Use only when the place is
	// unknown!
	LinkType_MixedIn_Area_Recording LinkType = 758
	// Links a release to the area it was mixed in. Use only when the place is
	// unknown!
	LinkType_MixedIn_Area_Release LinkType = 757
	// Describes the fact a person was contracted by a place as a mixing engineer.
	LinkType_MixingEngineerPosition_Artist_Place LinkType = 703
	// This is used to link a music video to the corresponding audio recording.
	LinkType_MusicVideo_Recording_Recording     LinkType = 857
	LinkType_MusicalRelationships_Artist_Artist LinkType = 106
	// This relationship type links an artist to their Myspace page.
	LinkType_Myspace_Artist_URL LinkType = 189
	// This relationship type links a label to its Myspace page.
	LinkType_Myspace_Label_URL LinkType = 215
	// This relationship type can be used to link a MusicBrainz place to the
	// equivalent entry in Myspace.
	LinkType_Myspace_Place_URL LinkType = 462
	// Indicates the official homepage for an artist.
	LinkType_OfficialHomepage_Artist_URL LinkType = 183
	// Indicates the official homepage for an event.
	LinkType_OfficialHomepage_Event_URL LinkType = 782
	// Indicates the official homepage for a place.
	LinkType_OfficialHomepage_Place_URL LinkType = 363
	// This relationship type is used to link a release group to an official
	// website created specifically for the release group.
	LinkType_OfficialHomepage_ReleaseGroup_URL LinkType = 287
	// Indicates the official homepage for a series.
	LinkType_OfficialHomepage_Series_URL LinkType = 745
	// Indicates the official homepage for a label.
	LinkType_OfficialSite_Label_URL LinkType = 219
	// This relationship type links an artist to their online community page(s). An
	// online community is a group where any member can comment and contribute
	// content. The artist may or may not be a member of the group. Examples
	// include forums, LiveJournal communities and groups on Facebook, Last.fm and
	// Flickr.
	LinkType_OnlineCommunity_Artist_URL LinkType = 185
	LinkType_OnlineData_Artist_URL      LinkType = 841
	LinkType_OnlineData_Label_URL       LinkType = 221
	LinkType_OnlineData_Place_URL       LinkType = 660
	// Links an event to an orchestra that performed in it.
	LinkType_Orchestra_Artist_Event LinkType = 807
	// This links two <a href="/doc/Work" title="Work">works</a> where one work is
	// an orchestration of the other.
	LinkType_Orchestration_Work_Work LinkType = 316
	// This indicates the person who orchestrated the recording. Orchestration is a
	// special type of arrangement. It means the adaptation of a composition for an
	// orchestra, done in a way that the musical substance remains essentially
	// unchanged. The orchestrator is also responsible for writing scores for an
	// orchestra, band, choral group, individual instrumentalist(s) or vocalist(s).
	// In practical terms it consists of deciding which instruments should play
	// which notes in a piece of music.
	LinkType_Orchestrator_Artist_Recording LinkType = 300
	// This indicates the person who orchestrated the release. Orchestration is a
	// special type of arrangement. It means the adaptation of a composition for an
	// orchestra, done in a way that the musical substance remains essentially
	// unchanged. The orchestrator is also responsible for writing scores for an
	// orchestra, band, choral group, individual instrumentalist(s) or vocalist(s).
	// In practical terms it consists of deciding which instruments should play
	// which notes in a piece of music.
	LinkType_Orchestrator_Artist_Release LinkType = 40
	// This indicates the person who orchestrated the work. Orchestration is a
	// special type of arrangement. It means the adaptation of a composition for an
	// orchestra, done in a way that the musical substance remains essentially
	// unchanged. The orchestrator is also responsible for writing scores for an
	// orchestra, band, choral group, individual instrumentalist(s) or vocalist(s).
	// In practical terms it consists of deciding which instruments should play
	// which notes in a piece of music.
	LinkType_Orchestrator_Artist_Work LinkType = 164
	// This relationship links an organist to the place(s) (most commonly religious
	// buildings) at which they are the resident organist.
	LinkType_Organist_Artist_Place LinkType = 856
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Area_URL LinkType = 730
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Artist_URL LinkType = 188
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Event_URL LinkType = 803
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Genre_URL      LinkType = 1086
	LinkType_OtherDatabases_Instrument_URL LinkType = 753
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Label_URL LinkType = 222
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Place_URL LinkType = 561
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Recording_URL LinkType = 306
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_ReleaseGroup_URL LinkType = 96
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Release_URL LinkType = 82
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_Series_URL LinkType = 746
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	LinkType_OtherDatabases_URL_Work LinkType = 273
	// This links two versions of a <a href="/doc/Work" title="Work">work</a>.
	LinkType_OtherVersion_Work_Work LinkType = 241
	// Indicates a parent-child relationship.
	LinkType_Parent_Artist_Artist LinkType = 109
	// This relationship type is <strong>deprecated</strong>! Please enter a
	// release with multiple discs as a single release containing multiple discs.
	LinkType_PartOfSet_Release_Release LinkType = 1
	// Designates that one area is contained by another.
	LinkType_PartOf_Area_Area LinkType = 356
	// Indicates that the artist is part of a series.
	LinkType_PartOf_Artist_Series LinkType = 996
	// Indicates that the event is part of a series.
	LinkType_PartOf_Event_Series LinkType = 802
	// Indicates that the recording is part of a series.
	LinkType_PartOf_Recording_Series LinkType = 740
	// Indicates that the release group is part of a series.
	LinkType_PartOf_ReleaseGroup_Series LinkType = 742
	// Indicates that the release is part of a series.
	LinkType_PartOf_Release_Series LinkType = 741
	// Indicates that the work is part of a series.
	LinkType_PartOf_Series_Work LinkType = 743
	// This indicates that an event is made up of multiple parts (e.g. a festival
	// happening on multiple venues over the course of a few days).
	LinkType_Parts_Event_Event LinkType = 818
	// parts
	LinkType_Parts_Instrument_Instrument LinkType = 739
	// This indicates that a place is part of another place.
	LinkType_Parts_Place_Place LinkType = 717
	// This indicates that a work is made up of multiple parts (e.g. an orchestral
	// suite broken into movements)
	LinkType_Parts_Work_Work              LinkType = 281
	LinkType_Performance_Artist_Recording LinkType = 122
	LinkType_Performance_Artist_Release   LinkType = 34
	// This is used to link works to their recordings.
	LinkType_Performance_Recording_Work LinkType = 278
	// Indicates an artist that performed on this recording.
	LinkType_Performer_Artist_Recording LinkType = 156
	// Indicates an artist that performed on this release.
	LinkType_Performer_Artist_Release LinkType = 51
	// Indicates an orchestra that performed on this recording.
	LinkType_PerformingOrchestra_Artist_Recording LinkType = 150
	// Indicates an orchestra that performed on this release.
	LinkType_PerformingOrchestra_Artist_Release LinkType = 45
	// This indicates a personal production label for an artist. A personal label
	// is a small label (usually a subdivision of a larger one) that exclusively
	// handles releases by that artist.
	LinkType_PersonalLabel_Artist_Label LinkType = 723
	// This indicates a personal publishing label for an artist. A personal
	// publishing label is a small label (usually a subdivision of a larger one)
	// that exclusively handles the rights to works by that artist.
	LinkType_PersonalPublisher_Artist_Label     LinkType = 724
	LinkType_PersonalRelationship_Artist_Artist LinkType = 113
	// This relationship indicates the artist is the <a
	// href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
	// copyright</a> holder for this recording.
	LinkType_PhonographicCopyright_Artist_Recording LinkType = 869
	// This relationship indicates the artist is the <a
	// href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
	// copyright</a> holder for this release.
	LinkType_PhonographicCopyright_Artist_Release LinkType = 710
	// This relationship indicates the label is the <a
	// href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
	// copyright</a> holder for this recording.
	LinkType_PhonographicCopyright_Label_Recording LinkType = 867
	// This relationship indicates the label is the <a
	// href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
	// copyright</a> holder for this release.
	LinkType_PhonographicCopyright_Label_Release LinkType = 711
	// This credits a person or agency whose photographs are included as part of a
	// recording.
	LinkType_Photography_Artist_Recording LinkType = 123
	// This credits a person or agency whose photographs are included as part of a
	// release.
	LinkType_Photography_Artist_Release LinkType = 20
	// This relationship type links an event to a promotional poster for the event.
	LinkType_Poster_Event_URL LinkType = 808
	// Indicates the area where the work had its first performance
	LinkType_Premiere_Area_Work LinkType = 715
	// Indicates the event where the work had its first performance
	LinkType_Premiere_Event_Work LinkType = 845
	// Indicates the place where the work had its first performance
	LinkType_Premiere_Place_Work LinkType = 716
	// Indicates an artist (generally a composer) this work was previously
	// attributed to, but who is currently confirmed (or very strongly suspected)
	// not to be the real author.
	LinkType_PreviousAttribution_Artist_Work LinkType = 834
	// This is used to link an artist to its primary concert venue.
	LinkType_PrimaryConcertVenue_Artist_Place LinkType = 714
	// Links a release to the area it was printed in.
	LinkType_PrintedIn_Area_Release LinkType = 849
	// Links a recording to the place it was produced at.
	LinkType_ProducedAt_Place_Recording LinkType = 825
	// Links a release to the place it was produced at.
	LinkType_ProducedAt_Place_Release LinkType = 824
	// Links a recording to the area it was produced in. Use only when the place is
	// unknown!
	LinkType_ProducedIn_Area_Recording LinkType = 827
	// Links a release to the area it was produced in. Use only when the place is
	// unknown!
	LinkType_ProducedIn_Area_Release LinkType = 826
	// This indicates that an artist was officially employed by a label as a
	// producer.
	LinkType_ProducerPosition_Artist_Label LinkType = 117
	// This indicates an artist who is responsible for the creative and practical
	// day-to-day aspects involved with making a musical recording.
	LinkType_Producer_Artist_Recording LinkType = 141
	// This indicates an artist who is responsible for the creative and practical
	// day-to-day aspects involved with making a musical recording.
	LinkType_Producer_Artist_Release     LinkType = 30
	LinkType_Production_Artist_Recording LinkType = 160
	LinkType_Production_Artist_Release   LinkType = 59
	LinkType_Production_Recording_URL    LinkType = 256
	LinkType_Production_Release_URL      LinkType = 72
	// This links a recording to the artist who did the programming for electronic
	// instruments used on the recording. In the most cases, the 'electronic
	// instrument' is either a synthesizer or a drum machine.
	LinkType_Programming_Artist_Recording LinkType = 132
	// This links a release to the artist who did the programming for electronic
	// instruments used on the release. In the most cases, the 'electronic
	// instrument' is either a synthesizer or a drum machine.
	LinkType_Programming_Artist_Release LinkType = 37
	// This indicates the organization that promotes (or contracts out promotion)
	// for a release. This is <strong>not</strong> the same concept as the <a
	// href="/doc/Label">record label</a>.
	LinkType_Promoted_Label_Release LinkType = 359
	// This indicates the organization which releases a release. This is
	// <strong>not</strong> the same concept as the <a href="/doc/Label">record
	// label</a>.
	LinkType_Published_Label_Release LinkType = 362
	// Indicates the publisher of this recording. This is <strong>not</strong> the
	// same concept as the <a href="/doc/Label">record label</a>.
	LinkType_Publishing_Artist_Recording LinkType = 127
	// Indicates the publisher of this release. This is <strong>not</strong> the
	// same concept as the <a href="/doc/Label">record label</a>.
	LinkType_Publishing_Artist_Release LinkType = 32
	// Indicates the publisher of this work. This is <strong>not</strong> the same
	// concept as the <a href="/doc/Label">record label</a>.
	LinkType_Publishing_Artist_Work LinkType = 161
	// This relationship is deprecated. To indicate work publishers, add label-work
	// relationships. To indicate (P) holders, use the phonographic copyright
	// relationship.
	LinkType_Publishing_Label_Recording LinkType = 206
	LinkType_Publishing_Label_Release   LinkType = 66
	// Indicates the publisher of this work. This is <strong>not</strong> the same
	// concept as the <a href="/doc/Label">record label</a>.
	LinkType_Publishing_Label_Work LinkType = 208
	// This is used to link to a page where the artist's releases can be purchased
	// for download.
	LinkType_PurchaseForDownload_Artist_URL LinkType = 176
	// This is used to link to a page where the recording can be purchased for
	// download.
	LinkType_PurchaseForDownload_Recording_URL LinkType = 254
	// This is used to link to a page where the release can be purchased for
	// download.
	LinkType_PurchaseForDownload_Release_URL LinkType = 74
	// This relationship type is used to link to a page where the artist's releases
	// can be purchased for mail order.
	LinkType_PurchaseForMailOrder_Artist_URL LinkType = 175
	// This relationship type is used to link to a page where the release can be
	// purchased for mail order.
	LinkType_PurchaseForMailOrder_Release_URL LinkType = 79
	// This links an artist to the equivalent entry at PureVolume.
	LinkType_Purevolume_Artist_URL LinkType = 174
	// Links a recording to the event it was recorded at.
	LinkType_RecordedAt_Event_Recording LinkType = 809
	// Links a release to the event it was recorded at.
	LinkType_RecordedAt_Event_Release LinkType = 810
	// Links a recording to the place it was recorded at.
	LinkType_RecordedAt_Place_Recording LinkType = 693
	// Links a release to the place it was recorded at.
	LinkType_RecordedAt_Place_Release LinkType = 695
	// Links a recording to the area it was recorded in. Use only when the place is
	// unknown!
	LinkType_RecordedIn_Area_Recording LinkType = 698
	// Links a release to the area it was recorded in. Use only when the place is
	// unknown!
	LinkType_RecordedIn_Area_Release LinkType = 699
	// This indicates that an artist had a recording contract with a label.
	LinkType_RecordingContract_Artist_Label LinkType = 121
	// Describes the fact a person was contracted by a place as a recording
	// engineer.
	LinkType_RecordingEngineerPosition_Artist_Place LinkType = 702
	// This describes an engineer responsible for committing the performance to
	// tape. This can be as complex as setting up the microphones, amplifiers, and
	// recording devices, or as simple as pressing the 'record' button on a
	// 4-track.
	LinkType_Recording_Artist_Recording LinkType = 128
	// This describes an engineer responsible for committing the performance to
	// tape. This can be as complex as setting up the microphones, amplifiers, and
	// recording devices, or as simple as pressing the 'record' button on a
	// 4-track.
	LinkType_Recording_Artist_Release LinkType = 36
	// related to
	LinkType_RelatedTo_Instrument_Instrument LinkType = 738
	// This relationship type is <strong>deprecated</strong>! <a
	// href="/doc/Style/Recording#Recordings_with_Different_Mastering">Different
	// remasters should be merged.</a>
	LinkType_Remaster_Recording_Recording LinkType = 236
	// This links two releases, where one is a <a
	// href="/doc/Mix_Terminology#remaster">remaster</a> of the other. This is
	// usually done to improve the audio quality or to adjust for more modern
	// playback equipment. The process generally doesn't involve changing the music
	// in any artistically important way. It may, however, result in recordings
	// that differ in length by a few seconds.
	LinkType_Remaster_Release_Release LinkType = 6
	// This links a <a href="/doc/Mix_Terminology#remix">remixed</a> recording to
	// the source recording.
	LinkType_Remix_Recording_Recording LinkType = 230
	// This links a <a href="/doc/Mix_Terminology#remix">remix</a> release group to
	// the source release group and is used to indicate that the release group
	// includes remixed versions of all (or most of) the tracks in the other
	// release group.
	LinkType_Remix_ReleaseGroup_ReleaseGroup LinkType = 9
	// Links a recording to the place it was remixed at.
	LinkType_RemixedAt_Place_Recording LinkType = 829
	// Links a release to the place it was remixed at.
	LinkType_RemixedAt_Place_Release LinkType = 828
	// Links a recording to the area it was remixed in. Use only when the place is
	// unknown!
	LinkType_RemixedIn_Area_Recording LinkType = 830
	// Links a release to the area it was remixed in. Use only when the place is
	// unknown!
	LinkType_RemixedIn_Area_Release LinkType = 831
	// This links a recording to the person who remixed it by taking one or more
	// other tracks, substantially altering them and mixing them together with
	// other material. Note that this includes the artist who created a mash-up or
	// used samples as well.
	LinkType_Remixer_Artist_Recording LinkType = 153
	// This links a release to the person who remixed it by taking one or more
	// other tracks, substantially altering them and mixing them together with
	// other material. Note that this includes the artist who created a mash-up or
	// used samples as well.
	LinkType_Remixer_Artist_Release                           LinkType = 47
	LinkType_RemixesAndCompilations_Artist_Recording          LinkType = 157
	LinkType_RemixesAndCompilations_Artist_Release            LinkType = 50
	LinkType_RemixesAndCompilations_Recording_Recording       LinkType = 234
	LinkType_RemixesAndCompilations_ReleaseGroup_ReleaseGroup LinkType = 13
	// This links a postponed event to the later rescheduled event.
	LinkType_RescheduledAs_Event_Event LinkType = 836
	// Indicates a webpage that reviews the event in question.
	LinkType_Review_Event_URL LinkType = 842
	// Indicates a webpage that reviews the release (group) in question.
	LinkType_Review_ReleaseGroup_URL LinkType = 94
	// Indicates that an artist revised a work. In most cases, this will be the
	// original composer revising the work at a later date.
	LinkType_RevisedBy_Artist_Work LinkType = 844
	// This links different revisions of the same <a href="/doc/Work"
	// title="Work">work</a>.
	LinkType_RevisionOf_Work_Work LinkType = 315
	// This indicates the rights society associated with a release. The rights
	// society is an organization which collects royalties on behalf of the
	// artists.
	LinkType_RightsSociety_Label_Release LinkType = 349
	// Indicates that the recording contains samples from material by the indicated
	// artist. Use this only if you really cannot figure out the particular
	// recording that has been sampled.
	LinkType_SamplesFromArtist_Artist_Recording LinkType = 154
	// Indicates that the release contains samples from material by the indicated
	// artist. Use this only if you really cannot figure out the particular
	// recording that has been sampled.
	LinkType_SamplesFromArtist_Artist_Release LinkType = 49
	// Indicates that the recording contains samples from another.
	LinkType_SamplesMaterial_Recording_Recording LinkType = 231
	// Indicates that the recording contains samples from this release.
	LinkType_SamplesMaterial_Recording_Release LinkType = 69
	// This describes a URL where a score / sheet music for the work can be found.
	LinkType_Score_URL_Work LinkType = 274
	// This is used to link an artist to its corresponding page in SecondHandSongs
	// database.
	LinkType_Secondhandsongs_Artist_URL LinkType = 307
	// This is used to link a release to its corresponding page in SecondHandSongs
	// database.
	LinkType_Secondhandsongs_Release_URL LinkType = 308
	// This is used to link a work to its corresponding page in SecondHandSongs
	// database.
	LinkType_Secondhandsongs_URL_Work LinkType = 280
	// This relationship type links an artist to its corresponding page at
	// setlist.fm
	LinkType_Setlistfm_Artist_URL LinkType = 816
	// This relationship type links an event to its corresponding page at
	// setlist.fm
	LinkType_Setlistfm_Event_URL LinkType = 811
	// This relationship type links a place to its corresponding page at setlist.fm
	LinkType_Setlistfm_Place_URL LinkType = 817
	// This relationship links the release of a show's episode (for example a
	// podcast) to the show notes for this episode.
	LinkType_ShowNotes_Release_URL LinkType = 729
	// This links two siblings (brothers or sisters).
	LinkType_Sibling_Artist_Artist LinkType = 110
	// This indicates that a single or EP release group includes at least one track
	// taken from an album release group. This allows a release group to be linked
	// to its associated singles and EPs.
	LinkType_SingleFrom_ReleaseGroup_ReleaseGroup LinkType = 11
	// A social network page is an artist's own profile page on a <a
	// href="https://en.wikipedia.org/wiki/Social_networking_service">social
	// network</a> which only they (or their management) can post content to. Other
	// people can create their own profiles and interact with the artist, e.g. by
	// adding them as a friend or by commenting on the things that they post.
	// Examples include Facebook pages and profiles, Last.fm users and accounts on
	// Twitter, Instagram and Flickr.
	LinkType_SocialNetwork_Artist_URL LinkType = 192
	// A social network page is an event's own page on a <a
	// href="https://en.wikipedia.org/wiki/Social_networking_service">social
	// network</a> which only people involved with the event can post content to.
	// Examples include Facebook pages and event entries, and accounts on Twitter,
	// Instagram and Flickr.
	LinkType_SocialNetwork_Event_URL LinkType = 783
	// A social network page is a label's own page on a <a
	// href="https://en.wikipedia.org/wiki/Social_networking_service">social
	// network</a> which only people involved with the label can post content to.
	// Examples include Facebook pages, and accounts on Twitter, Instagram and
	// Flickr.
	LinkType_SocialNetwork_Label_URL LinkType = 218
	// A social network page is a place's own page on a <a
	// href="https://en.wikipedia.org/wiki/Social_networking_service">social
	// network</a> which only people involved with the place can post content to.
	// Examples include Facebook pages, and accounts on Twitter, Instagram and
	// Flickr.
	LinkType_SocialNetwork_Place_URL LinkType = 429
	// A social network page is a page for a series on a <a
	// href="https://en.wikipedia.org/wiki/Social_networking_service">social
	// network</a> which only people involved with the series can post content to.
	// Examples include Facebook pages, and accounts on Twitter, Instagram and
	// Flickr.
	LinkType_SocialNetwork_Series_URL LinkType = 784
	// This links an entity to the appropriate listing in the Songfacts database, a
	// user contributed database concerned with the stories behind the songs.
	LinkType_Songfacts_URL_Work LinkType = 289
	// This relationship type links an artist to its corresponding page at
	// Songkick.
	LinkType_Songkick_Artist_URL LinkType = 785
	// This relationship type links an event to its corresponding page at Songkick.
	LinkType_Songkick_Event_URL LinkType = 786
	// This relationship type links a place to its corresponding page at Songkick.
	LinkType_Songkick_Place_URL LinkType = 787
	// This describes an engineer responsible for ensuring that the sounds that the
	// artists make reach the microphones sounding pleasant, without unwanted
	// resonance or noise. Sometimes known as acoustical engineering.
	LinkType_Sound_Artist_Recording LinkType = 133
	// This describes an engineer responsible for ensuring that the sounds that the
	// artists make reach the microphones sounding pleasant, without unwanted
	// resonance or noise. Sometimes known as acoustical engineering.
	LinkType_Sound_Artist_Release LinkType = 29
	// This links an artist to its profile at SoundCloud.
	LinkType_Soundcloud_Artist_URL LinkType = 291
	// This links a label to its profile at SoundCloud.
	LinkType_Soundcloud_Label_URL LinkType = 290
	// This links a series (most commonly, but not necessarily always, a music
	// festival) to its official page at SoundCloud.
	LinkType_Soundcloud_Series_URL LinkType = 870
	// This relationship type is used to link an artist to a site where music can
	// be legally streamed for free, e.g. Spotify.
	LinkType_StreamingMusic_Artist_URL LinkType = 194
	// This relationship type is used to link a track to a site where the track can
	// be legally streamed for free, such as Spotify for audio tracks or YouTube
	// for videos.
	LinkType_StreamingMusic_Recording_URL LinkType = 268
	// This relationship type is used to link a release to a site where the tracks
	// can be legally streamed for free, e.g. Spotify.
	LinkType_StreamingMusic_Release_URL LinkType = 85
	// This relationship type is used to link a track to a site where the track can
	// be legally streamed for a subscription fee, e.g. Tidal. If the site allows
	// free streaming, use "free streaming" instead.
	LinkType_StreamingPaid_Recording_URL LinkType = 979
	// This relationship type is used to link a release to a site where the tracks
	// can be legally streamed for a subscription fee, e.g. Tidal.
	LinkType_StreamingPaid_Release_URL LinkType = 980
	// This links a subgroup to the group from which it was created. This
	// relationship type is the functional equivalent of the <a
	// href="/relationship/5be4c609-9afa-4ea0-910b-12ffb71e3821">member of band
	// type</a> for group-group relationships.
	LinkType_Subgroup_Artist_Artist LinkType = 722
	// Links a series to another series that exists within it.
	LinkType_Subseries_Series_Series LinkType = 823
	// type of
	LinkType_Subtype_Instrument_Instrument LinkType = 736
	// Links an event to (one of) its support act(s).
	LinkType_SupportAct_Artist_Event LinkType = 799
	// Indicates an artist doing long-time instrumental or vocal support for
	// another one on albums and/or at concerts. This is a person-to-artist
	// relationship that normally applies to well-known solo artists, although it
	// can sometimes apply to groups.
	LinkType_SupportingMusician_Artist_Artist LinkType = 104
	// This indicates that a release was released in support of another
	// release.This allows a release to be linked to its supporting singles, EPs,
	// and remix releases. A 'supporting release' is one which is released to
	// increase sales of an album or to create publicity for an album.
	LinkType_SupportingRelease_Release_Release LinkType = 3
	// This relationship indicates that a person was another's teacher/student.
	LinkType_Teacher_Artist_Artist LinkType = 847
	// This relationship links a concert tour to the artist(s) the tour is by.
	LinkType_Tour_Artist_Series LinkType = 859
	// This indicates that one release is identical to another release, but that
	// the release title and track titles have been either translated (into another
	// language) or transliterated (into another script).
	LinkType_TranslTracklisting_Release_Release LinkType = 2
	// This relationship specifies that an artist is a <a
	// href="http://en.wikipedia.org/wiki/Tribute_act">tribute</a> to another
	// specific artist/band; that is, it primarily performs covers of that artist.
	// They may also be referred to as cover bands. Some tribute artists may name
	// themselves, dress, and/or act similarly to the artists they pay tribute to.
	LinkType_Tribute_Artist_Artist LinkType = 728
	// This links a release group to an artist, to indicate that it is a tribute
	// album. Tribute albums often have a title in the form "A Tribute to Artist",
	// and they consist of covers of songs by the target artist, played by other
	// (sometimes very unknown) bands, to honor the target artist. Often they are
	// various artist compilations, but a single artist can perform the entire
	// tribute album.
	LinkType_Tribute_Artist_ReleaseGroup LinkType = 65
	// This relationship type links an artist to its corresponding page at <a
	// href="http://vgmdb.net/">VGMdb</a>. VGMdb is a community project dedicated
	// to cataloguing the music of video games and anime.
	LinkType_VGMdb_Artist_URL LinkType = 191
	// This relationship type links an event to its corresponding page at <a
	// href="http://vgmdb.net/">VGMdb</a>. VGMdb is a community project dedicated
	// to cataloguing the music of video games and anime.
	LinkType_VGMdb_Event_URL LinkType = 788
	// This relationship type links a label to its corresponding page at <a
	// href="http://vgmdb.net/">VGMdb</a>. VGMdb is a community project dedicated
	// to cataloguing the music of video games and anime.
	LinkType_VGMdb_Label_URL LinkType = 210
	// This relationship type links a release to its corresponding page <a
	// href="http://vgmdb.net/">VGMdb</a>. VGMdb is a community project dedicated
	// to cataloguing the music of video games and anime.
	LinkType_VGMdb_Release_URL LinkType = 86
	// This points to the <a href="//viaf.org/">VIAF</a> page for this artist. VIAF
	// is an international project to make a common authority file available to
	// libraries across the world. An authority file is similar to an MBID for
	// libraries. (<a
	// href="//en.wikipedia.org/wiki/Virtual_International_Authority_File">more
	// information on Wikipedia</a>)
	LinkType_VIAF_Artist_URL LinkType = 310
	// This points to the <a href="//viaf.org/">VIAF</a> page for this label. VIAF
	// is an international project to make a common authority file available to
	// libraries across the world. An authority file is similar to an MBID for
	// libraries. (<a
	// href="//en.wikipedia.org/wiki/Virtual_International_Authority_File">more
	// information on Wikipedia</a>)
	LinkType_VIAF_Label_URL LinkType = 311
	// This points to the <a href="//viaf.org/">VIAF</a> page for this work. VIAF
	// is an international project to make a common authority file available to
	// libraries across the world. An authority file is similar to an MBID for
	// libraries. (<a
	// href="//en.wikipedia.org/wiki/Virtual_International_Authority_File">more
	// information on Wikipedia</a>)
	// <br/><br/>
	// <strong>Note:</strong> Works in VIAF aren't very detailed. Only add links to
	// MusicBrainz works if you're absolutely sure it's the same work.
	LinkType_VIAF_URL_Work LinkType = 312
	// This indicates that an artist appears on a music video, but doesn't actually
	// perform on the audio track.
	LinkType_VideoAppearance_Artist_Recording LinkType = 858
	// This links an artist to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	LinkType_VideoChannel_Artist_URL LinkType = 303
	// This links an event to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	LinkType_VideoChannel_Event_URL LinkType = 804
	// This links a label to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	LinkType_VideoChannel_Label_URL LinkType = 304
	// This links a place to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	LinkType_VideoChannel_Place_URL LinkType = 495
	// This links a series to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	LinkType_VideoChannel_Series_URL LinkType = 805
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_VocalArranger_Artist_Recording LinkType = 298
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_VocalArranger_Artist_Release LinkType = 296
	// This indicates the artist who arranged a tune into a form suitable for
	// performance. 'Arrangement' is used as a catch-all term for all processes
	// that turn a composition into a form that can be played by a specific type of
	// ensemble.
	LinkType_VocalArranger_Artist_Work LinkType = 294
	// Indicates a musician doing long-time vocal support for another one on albums
	// and/or at concerts. This is a person-to-artist relationship that normally
	// applies to well-known solo artists, although it can sometimes apply to
	// groups.
	LinkType_VocalSupportingMusician_Artist_Artist LinkType = 107
	// Indicates an artist that performed vocals on this recording.
	LinkType_Vocal_Artist_Recording LinkType = 149
	// Indicates an artist that performed vocals on this release.
	LinkType_Vocal_Artist_Release LinkType = 60
	// This links an (fictional) artist to the person that voice acted it.
	LinkType_VoiceActor_Artist_Artist LinkType = 292
	// Points to the Wikidata page for this area.
	LinkType_Wikidata_Area_URL LinkType = 358
	// Points to the Wikidata page for this artist.
	LinkType_Wikidata_Artist_URL LinkType = 352
	// Points to the Wikidata page for this event.
	LinkType_Wikidata_Event_URL LinkType = 790
	// Points to the Wikidata page for this genre, and will be used to fetch
	// Wikipedia summaries
	LinkType_Wikidata_Genre_URL LinkType = 1087
	// wikidata
	LinkType_Wikidata_Instrument_URL LinkType = 733
	// Points to the Wikidata page for this label.
	LinkType_Wikidata_Label_URL LinkType = 354
	// Points to the Wikidata page for this place
	LinkType_Wikidata_Place_URL LinkType = 594
	// Points to the Wikidata page for this release group.
	LinkType_Wikidata_ReleaseGroup_URL LinkType = 353
	// Points to the Wikidata page for this series.
	LinkType_Wikidata_Series_URL LinkType = 749
	// Points to the Wikidata page for this work.
	LinkType_Wikidata_URL_Work LinkType = 351
	// Points to the Wikipedia page for this area.
	LinkType_Wikipedia_Area_URL LinkType = 355
	// Points to the Wikipedia page for this artist.
	LinkType_Wikipedia_Artist_URL LinkType = 179
	// Points to the Wikipedia page for this event.
	LinkType_Wikipedia_Event_URL LinkType = 789
	// wikipedia
	LinkType_Wikipedia_Instrument_URL LinkType = 731
	// This is used to link a label to its corresponding Wikipedia page.
	LinkType_Wikipedia_Label_URL LinkType = 216
	// Points to the Wikipedia page for this place
	LinkType_Wikipedia_Place_URL LinkType = 595
	// Points to the Wikipedia page for this album.
	LinkType_Wikipedia_ReleaseGroup_URL LinkType = 89
	// Points to the Wikipedia page for this series.
	LinkType_Wikipedia_Series_URL LinkType = 744
	// Points to the Wikipedia page for this work.
	LinkType_Wikipedia_URL_Work LinkType = 279
	// This relationship is used to link a release to the artist responsible for
	// writing the music and/or the words (lyrics, libretto, etc.), when no more
	// specific information is available. If possible, the more specific composer,
	// lyricist and/or librettist types should be used, rather than this
	// relationship type.
	LinkType_Writer_Artist_Release LinkType = 54
	// This relationship is used to link a work to the artist responsible for
	// writing the music and/or the words (lyrics, libretto, etc.), when no more
	// specific information is available. If possible, the more specific composer,
	// lyricist and/or librettist types should be used, rather than this
	// relationship type.
	LinkType_Writer_Artist_Work LinkType = 167
	// This links an artist to the equivalent entry at YouTube.
	LinkType_YouTube_Artist_URL LinkType = 193
	// This relationship type can be used to link an event to the equivalent entry
	// in YouTube. URLs should follow the format
	// http://www.youtube.com/user/&lt;username&gt;
	LinkType_YouTube_Event_URL LinkType = 791
	// This links a label to the equivalent entry at YouTube.
	LinkType_YouTube_Label_URL LinkType = 225
	// This relationship type can be used to link a place to the equivalent entry
	// in YouTube. URLs should follow the format
	// http://www.youtube.com/user/<username>
	LinkType_YouTube_Place_URL LinkType = 528
	// This relationship type can be used to link a series to the equivalent entry
	// in YouTube. URLs should follow the format
	// http://www.youtube.com/user/&lt;username&gt;
	LinkType_YouTube_Series_URL LinkType = 792
)

// MediumFormat describes a medium's format (e.g. CD, cassette, digital media).
type MediumFormat string

const (
	MediumFormat_CD                MediumFormat = "CD"
	MediumFormat_DVD               MediumFormat = "DVD"
	MediumFormat_SACD              MediumFormat = "SACD"
	MediumFormat_DualDisc          MediumFormat = "DualDisc"
	MediumFormat_Other             MediumFormat = "Other"
	MediumFormat_LaserDisc         MediumFormat = "LaserDisc"
	MediumFormat_MiniDisc          MediumFormat = "MiniDisc"
	MediumFormat_Vinyl             MediumFormat = "Vinyl"
	MediumFormat_Cassette          MediumFormat = "Cassette"
	MediumFormat_Cartridge         MediumFormat = "Cartridge"
	MediumFormat_ReelToReel        MediumFormat = "Reel-to-reel"
	MediumFormat_DAT               MediumFormat = "DAT"
	MediumFormat_DigitalMedia      MediumFormat = "Digital Media"
	MediumFormat_WaxCylinder       MediumFormat = "Wax Cylinder"
	MediumFormat_PianoRoll         MediumFormat = "Piano Roll"
	MediumFormat_DCC               MediumFormat = "DCC"
	MediumFormat_HDDVD             MediumFormat = "HD-DVD"
	MediumFormat_DVDAudio          MediumFormat = "DVD-Audio"
	MediumFormat_DVDVideo          MediumFormat = "DVD-Video"
	MediumFormat_BluRay            MediumFormat = "Blu-ray"
	MediumFormat_VHS               MediumFormat = "VHS"
	MediumFormat_VCD               MediumFormat = "VCD"
	MediumFormat_SVCD              MediumFormat = "SVCD"
	MediumFormat_Betamax           MediumFormat = "Betamax"
	MediumFormat_HDCD              MediumFormat = "HDCD"
	MediumFormat_USBFlashDrive     MediumFormat = "USB Flash Drive"
	MediumFormat_slotMusic         MediumFormat = "slotMusic"
	MediumFormat_UMD               MediumFormat = "UMD"
	MediumFormat_7Vinyl            MediumFormat = "7\" Vinyl"
	MediumFormat_10Vinyl           MediumFormat = "10\" Vinyl"
	MediumFormat_12Vinyl           MediumFormat = "12\" Vinyl"
	MediumFormat_CDR               MediumFormat = "CD-R"
	MediumFormat_8cmCD             MediumFormat = "8cm CD"
	MediumFormat_BluSpecCD         MediumFormat = "Blu-spec CD"
	MediumFormat_SHMCD             MediumFormat = "SHM-CD"
	MediumFormat_HQCD              MediumFormat = "HQCD"
	MediumFormat_HybridSACD        MediumFormat = "Hybrid SACD"
	MediumFormat_CDG               MediumFormat = "CD+G"
	MediumFormat_8cmCDG            MediumFormat = "8cm CD+G"
	MediumFormat_CDV               MediumFormat = "CDV"
	MediumFormat_EnhancedCD        MediumFormat = "Enhanced CD"
	MediumFormat_DataCD            MediumFormat = "Data CD"
	MediumFormat_DTSCD             MediumFormat = "DTS CD"
	MediumFormat_Playbutton        MediumFormat = "Playbutton"
	MediumFormat_MusicCard         MediumFormat = "Music Card"
	MediumFormat_DVDplus           MediumFormat = "DVDplus"
	MediumFormat_VinylDisc         MediumFormat = "VinylDisc"
	MediumFormat_35FloppyDisk      MediumFormat = "3.5\" Floppy Disk"
	MediumFormat_EdisonDiamondDisc MediumFormat = "Edison Diamond Disc"
	// Flexi-discs are phonograph records made of a thin, flexible vinyl sheet with
	// a molded-in groove, designed to be playable on a normal phonograph
	// turntable.
	MediumFormat_FlexiDisc  MediumFormat = "Flexi-disc"
	MediumFormat_7FlexiDisc MediumFormat = "7\" Flexi-disc"
	// Shellac records were the most predominant type of gramophone record during
	// the first half of the 20th century.
	MediumFormat_Shellac   MediumFormat = "Shellac"
	MediumFormat_10Shellac MediumFormat = "10\" Shellac"
	MediumFormat_12Shellac MediumFormat = "12\" Shellac"
	MediumFormat_7Shellac  MediumFormat = "7\" Shellac"
	MediumFormat_SHMSACD   MediumFormat = "SHM-SACD"
	// 90 rpm, vertical-cut shellac discs, produced by the Pathé label from 1906
	// to 1932.
	MediumFormat_PatheDisc MediumFormat = "Pathé disc"
	// Video High Density (VHD) was a videodisc format which was marketed
	// predominantly in Japan by JVC.
	MediumFormat_VHD MediumFormat = "VHD"
	// The Capacitance Electronic Disc (CED) is an analog video disc playback
	// system developed by RCA, in which video and audio could be played back on a
	// TV set using a special needle and high-density groove system similar to
	// phonograph records.
	MediumFormat_CED MediumFormat = "CED"
	// Copy Control CD (CCCD) is an umbrella term for CDs released circa 2001-2006
	// containing software that is ostensibly designed to prevent the CD from being
	// ripped. There are a number of software variants: the most well-known are
	// Macrovision's Cactus Data Shield (CDS) and SunnComm's MediaMax.
	MediumFormat_CopyControlCD MediumFormat = "Copy Control CD"
)

// ReleaseGroupType describes a release group.
// A release group can be assigned a single primary type and multiple secondary types.
type ReleaseGroupType string

const (
	ReleaseGroupType_Album         ReleaseGroupType = "Album"          // primary
	ReleaseGroupType_Single        ReleaseGroupType = "Single"         // primary
	ReleaseGroupType_EP            ReleaseGroupType = "EP"             // primary
	ReleaseGroupType_Other         ReleaseGroupType = "Other"          // primary
	ReleaseGroupType_Broadcast     ReleaseGroupType = "Broadcast"      // primary
	ReleaseGroupType_Compilation   ReleaseGroupType = "Compilation"    // secondary
	ReleaseGroupType_Soundtrack    ReleaseGroupType = "Soundtrack"     // secondary
	ReleaseGroupType_Spokenword    ReleaseGroupType = "Spokenword"     // secondary
	ReleaseGroupType_Interview     ReleaseGroupType = "Interview"      // secondary
	ReleaseGroupType_Audiobook     ReleaseGroupType = "Audiobook"      // secondary
	ReleaseGroupType_Live          ReleaseGroupType = "Live"           // secondary
	ReleaseGroupType_Remix         ReleaseGroupType = "Remix"          // secondary
	ReleaseGroupType_DJMix         ReleaseGroupType = "DJ-mix"         // secondary
	ReleaseGroupType_MixtapeStreet ReleaseGroupType = "Mixtape/Street" // secondary
	ReleaseGroupType_Demo          ReleaseGroupType = "Demo"           // secondary
)

// ReleasePackaging describes a release's packaging.
type ReleasePackaging string

const (
	// The traditional CD case, made of hard, brittle plastic.
	ReleasePackaging_JewelCase ReleasePackaging = "Jewel Case"
	// A thinner jewel case, commonly used for CD singles.
	ReleasePackaging_SlimJewelCase        ReleasePackaging = "Slim Jewel Case"
	ReleasePackaging_Digipak              ReleasePackaging = "Digipak"
	ReleasePackaging_CardboardPaperSleeve ReleasePackaging = "Cardboard/Paper Sleeve"
	ReleasePackaging_Other                ReleasePackaging = "Other"
	ReleasePackaging_None                 ReleasePackaging = "None"
)

// ReleaseStatus describes a release's status.
type ReleaseStatus string

const (
	// Any release officially sanctioned by the artist and/or their record company.
	// Most releases will fit into this category.
	ReleaseStatus_Official ReleaseStatus = "Official"
	// A give-away release or a release intended to promote an upcoming official
	// release (e.g. pre-release versions, releases included with a magazine,
	// versions supplied to radio DJs for air-play).
	ReleaseStatus_Promotion ReleaseStatus = "Promotion"
	// An unofficial/underground release that was not sanctioned by the artist
	// and/or the record company. This includes unofficial live recordings and
	// pirated releases.
	ReleaseStatus_Bootleg ReleaseStatus = "Bootleg"
	// An alternate version of a release where the titles have been changed. These
	// don't correspond to any real release and should be linked to the original
	// release using the transl(iter)ation relationship.
	ReleaseStatus_PseudoRelease ReleaseStatus = "Pseudo-Release"
)
