// This file is derived from https://github.com/metabrainz/musicbrainz-server,
// which is licensed under GNU General Public License (GPL) Version 2 or later.
// This license is located at seed/COPYING-enums.md.

package seed

// This file was automatically generated from a copy of
// https://raw.githubusercontent.com/metabrainz/musicbrainz-server/master/t/sql/initial.sql
// downloaded at 2022-10-29 17:16:03 UTC.
// It can be regenerated by running "go generate".

// LinkType is an ID describing a link between two MusicBrainz entities.
// It sadly doesn't appear to enumerate all possible values. There are 173
// additional link types with translations in po/relationships.pot, many of
// which don't appear to be referenced anywhere else in the server repo.
type LinkType int

const (
	// This is used to link an artist to its corresponding page on Allmusic.
	AllMusic_Artist_URL_Link LinkType = 283
	// This is used to link a genre to its corresponding page on Allmusic.
	AllMusic_Genre_URL_Link LinkType = 1093
	// This is used to link a recording to its corresponding page on Allmusic.
	AllMusic_Recording_URL_Link LinkType = 285
	// This is used to link a release group to its corresponding page on Allmusic.
	AllMusic_ReleaseGroup_URL_Link LinkType = 284
	// This is used to link a release to its corresponding page on Allmusic.
	AllMusic_Release_URL_Link LinkType = 755
	// This is used to link a work to its corresponding page on Allmusic.
	AllMusic_URL_Work_Link LinkType = 286
	// This links a MusicBrainz release to the equivalent entry at Amazon and will
	// often provide cover art if there is no cover art in the <a
	// href="/doc/Cover_Art_Archive">Cover Art Archive</a>.
	AmazonASIN_Release_URL_Link LinkType = 77
	// Designates that a work is or was the anthem for an area
	Anthem_Area_Work_Link LinkType = 357
	// Links a recording to the place it was arranged at.
	ArrangedAt_Place_Recording_Link LinkType = 866
	// Links a release to the place it was arranged at.
	ArrangedAt_Place_Release_Link LinkType = 865
	// Links a recording to the area it was arranged in. Use only when the place is
	// unknown!
	ArrangedIn_Area_Recording_Link LinkType = 864
	// Links a release to the area it was arranged in. Use only when the place is
	// unknown!
	ArrangedIn_Area_Release_Link LinkType = 863
	// This links two <a href="/doc/Work" title="Work">works</a> where one work is
	// an arrangement of the other.
	Arrangement_Work_Work_Link LinkType = 350
	// This indicates that a person or agency did the art direction for the
	// recording.
	ArtDirection_Artist_Recording_Link LinkType = 137
	// This indicates that a person or agency did the art direction for the
	// release.
	ArtDirection_Artist_Release_Link LinkType = 18
	// This indicates a person or agency which is responsible for talent scouting,
	// overseeing the artistic development of an artist, and acting as liaison
	// between artists and the labels.
	ArtistsAndRepertoire_Artist_Recording_Link LinkType = 135
	// This indicates a person or agency which is responsible for talent scouting,
	// overseeing the artistic development of an artist, and acting as liaison
	// between artists and the labels.
	ArtistsAndRepertoire_Artist_ReleaseGroup_Link LinkType = 62
	// This relationship type links instruments to genres they are commonly used
	// in.
	AssociatedInstrument_Genre_Instrument_Link LinkType = 1090
	// This describes an engineer involved with the machines used to generate
	// sound, such as effects processors and digital audio equipment used to modify
	// or manipulate sound in either an analogue or digital form.
	Audio_Artist_Recording_Link LinkType = 140
	// This describes an engineer involved with the machines used to generate
	// sound, such as effects processors and digital audio equipment used to modify
	// or manipulate sound in either an analogue or digital form.
	Audio_Artist_Release_Link LinkType = 31
	// Links a release with an event where it was available. This is intended for
	// event-exclusive releases and/or releases available at events before the
	// official launch date, not for every release in the merchandise stall.
	AvailableAt_Event_Release_Link LinkType = 795
	// This links a recording to the balance engineer who engineered it.
	Balance_Artist_Recording_Link LinkType = 726
	// This links a release to the balance engineer who engineered it.
	Balance_Artist_Release_Link LinkType = 727
	// This links an artist to its page at Bandcamp.
	Bandcamp_Artist_URL_Link LinkType = 718
	// This links a genre to its page at Bandcamp.
	Bandcamp_Genre_URL_Link LinkType = 1092
	// This links a label to its page at Bandcamp.
	Bandcamp_Label_URL_Link LinkType = 719
	// This relationship type links an artist to its corresponding page at
	// Bandsintown.
	Bandsintown_Artist_URL_Link LinkType = 862
	// This relationship type links an event to its corresponding page at
	// Bandsintown.
	Bandsintown_Event_URL_Link LinkType = 860
	// This relationship type links a place to its corresponding page at
	// Bandsintown.
	Bandsintown_Place_URL_Link LinkType = 861
	// This links an artist to an online biography for that artist.
	Biography_Artist_URL_Link LinkType = 182
	// This relationship type is used to link an artist to their blog.
	Blog_Artist_URL_Link LinkType = 199
	// This relationship type is used to link a label to its blog.
	Blog_Label_URL_Link LinkType = 224
	// This relationship type can be used to link a place to its blog
	Blog_Place_URL_Link LinkType = 627
	// Points to the BookBrainz page for this artist.
	BookBrainz_Artist_URL_Link LinkType = 852
	// Points to the BookBrainz page for this label.
	BookBrainz_Label_URL_Link LinkType = 851
	// Points to the BookBrainz page for this release group.
	BookBrainz_ReleaseGroup_URL_Link LinkType = 853
	// Points to the BookBrainz page for this release.
	BookBrainz_Release_URL_Link LinkType = 850
	// Points to the BookBrainz page for this work.
	BookBrainz_URL_Work_Link LinkType = 854
	// This credits a person who was responsible for booking the studio or
	// performance venue where the recording was recorded.
	Booking_Artist_Recording_Link LinkType = 134
	// This credits a person who was responsible for booking the studio or
	// performance venue where the release was recorded.
	Booking_Artist_Release_Link          LinkType = 23
	BusinessAssociation_Label_Label_Link LinkType = 205
	// This links to a catalog or list of records published by the label.
	CatalogSite_Label_URL_Link LinkType = 212
	// This relationship is used to link a catalogue work series to a person who
	// was involved in compiling it.
	Catalogued_Artist_Series_Link       LinkType = 751
	Children_Instrument_Instrument_Link LinkType = 735
	// This indicates the chorus master of a choir which performed on this
	// recording.
	ChorusMaster_Artist_Recording_Link LinkType = 152
	// This indicates the chorus master of a choir which performed on this release.
	ChorusMaster_Artist_Release_Link LinkType = 53
	// This indicates that a recording is a compilation of several other
	// recordings. This applies to one long recording that contains multiple songs,
	// one after the other, in which the audio material of the original recordings
	// has not been altered. If the tracks are pitched or blended into each other,
	// the <a href="/relationship/451076df-61cf-46ab-9921-555cab2f050d">DJ-mix
	// relationship type</a> may be more appropriate.
	Compilation_Recording_Recording_Link LinkType = 228
	// This indicates the person who selected the tracks and the sequence for a
	// compilation. This applies to one long recording which contains multiple
	// songs, one after the other. If the tracks are pitched or blended into each
	// other, it is more appropriate to credit this person as a <a
	// href="/relationship/28338ee6-d578-485a-bb53-61dbfd7c6545">DJ-mixer</a>.
	Compiler_Artist_Recording_Link LinkType = 147
	// This indicates the person who selected the tracks and the sequence for a
	// compilation. If the tracks are pitched or blended into each other, it is
	// more appropriate to credit this person as a <a
	// href="/relationship/9162dedd-790c-446c-838e-240f877dbfe2">DJ-mixer</a>.
	Compiler_Artist_Release_Link LinkType = 48
	// This links a group (often an orchestra) to a composer who has a
	// composer-in-residence position with the group.
	ComposerInResidence_Artist_Artist_Link LinkType = 855
	// Indicates the composer for this release, i.e. the artist who wrote the music
	// (not necessarily the lyrics).
	Composer_Artist_Release_Link LinkType = 55
	// Indicates the composer for this work, i.e. the artist who wrote the music
	// (not necessarily the lyrics).
	Composer_Artist_Work_Link       LinkType = 168
	Composition_Artist_Release_Link LinkType = 58
	Composition_Artist_Work_Link    LinkType = 170
	// This indicates an artist who was the concertmaster/leader for an orchestra
	// or band on this recording.
	Concertmaster_Artist_Recording_Link LinkType = 760
	// This indicates an artist who was the concertmaster/leader for an orchestra
	// or band on this release.
	Concertmaster_Artist_Release_Link LinkType = 759
	// This indicates that a person is, or was, a conductor for a group.
	ConductorPosition_Artist_Artist_Link LinkType = 305
	// Links an event to an artist that was a conductor in it.
	Conductor_Artist_Event_Link LinkType = 806
	// This indicates an artist who conducted an orchestra, band or choir on this
	// recording.
	Conductor_Artist_Recording_Link LinkType = 151
	// This indicates an artist who conducted an orchestra, band or choir on this
	// release.
	Conductor_Artist_Release_Link LinkType = 46
	Contract_Artist_Label_Link    LinkType = 119
	// This relationship indicates the artist is the copyright holder for this
	// release.
	Copyright_Artist_Release_Link LinkType = 709
	// This relationship indicates the label is the copyright holder for this
	// release.
	Copyright_Label_Release_Link                     LinkType = 708
	CoversAndVersions_Recording_Recording_Link       LinkType = 233
	CoversAndVersions_ReleaseGroup_ReleaseGroup_Link LinkType = 12
	CoversAndVersions_Release_Release_Link           LinkType = 4
	// This credits a person or agency who provided some kind of general creative
	// inspiration during the recording of this recording, without actually
	// contributing to the writing or performance.
	CreativeDirection_Artist_Recording_Link LinkType = 146
	// This credits a person or agency who provided some kind of general creative
	// inspiration during the recording of this release group, without actually
	// contributing to the writing or performance.
	CreativeDirection_Artist_ReleaseGroup_Link LinkType = 63
	// This indicates that an artist was officially employed by a label in a
	// creative position, such as photographer or graphic designer.
	CreativePosition_Artist_Label_Link LinkType = 115
	// This links a release to the relevant crowdfunding project at a crowdfunding
	// site like Kickstarter or Indiegogo.
	Crowdfunding_Release_URL_Link LinkType = 906
	// This is used to link a <a href="/doc/Mix_Terminology#DJ_mix">DJ-mixed</a>
	// recording to each of the source recordings. See <a
	// href="/relationship/28338ee6-d578-485a-bb53-61dbfd7c6545">DJ-mixer</a> for
	// crediting the person who created the DJ-mix.
	DJMix_Recording_Recording_Link LinkType = 227
	// This is used to link a release group containing a <a
	// href="/doc/Mix_Terminology#DJ_mix">DJ-mixed</a> version of a release to the
	// release group containing the source release. See <a
	// href="/relationship/9162dedd-790c-446c-838e-240f877dbfe2">DJ-mixer</a> for
	// crediting the person who created the DJ-mix.
	DJMix_ReleaseGroup_ReleaseGroup_Link LinkType = 8
	// This links a release group to an artist it is dedicated to. This is for
	// dedications such as "This album is dedicated to the memory of Artist" - for
	// tribute albums consisting of covers of the artist, use the <a
	// href="/relationship/5e2907db-49ec-4a48-9f11-dfb99d2603ff">tribute
	// relationship</a>.
	DedicatedTo_Artist_ReleaseGroup_Link LinkType = 868
	// This indicates the work is dedicated to a specific person. This is most
	// common for classical works, but also exists in other genres to a degree.
	Dedication_Artist_Work_Link LinkType = 846
	// derived from
	Derivation_Instrument_Instrument_Link LinkType = 737
	// This indicates a person or agency who did design or illustration for the
	// track.
	Designillustration_Artist_Recording_Link LinkType = 130
	// This indicates a person or agency who did design or illustration for the
	// release.
	Designillustration_Artist_Release_Link LinkType = 19
	// This link points to a page for a particular release within a discography for
	// an artist or label.
	DiscographyEntry_Release_URL_Link LinkType = 288
	// This links an artist to an online discography of their works. The
	// discography should provide a summary of most, if not all, releases by the
	// artist, and be as comprehensive as possible.
	DiscographyPage_Artist_URL_Link   LinkType = 184
	Discography_Artist_URL_Link       LinkType = 171
	Discography_ReleaseGroup_URL_Link LinkType = 88
	// This is used to link the Discogs page for this artist.
	Discogs_Artist_URL_Link LinkType = 180
	// This is used to link the Discogs page for this genre/style.
	Discogs_Genre_URL_Link LinkType = 1089
	// This is used to link the Discogs page for this label.
	Discogs_Label_URL_Link LinkType = 217
	// This is used to link a place to the equivalent entry in Discogs.
	Discogs_Place_URL_Link LinkType = 705
	// This is used to link the Discogs page for this release group.
	Discogs_ReleaseGroup_URL_Link LinkType = 90
	// This is used to link the Discogs page for this release.
	Discogs_Release_URL_Link LinkType = 76
	// This is used to link a series to the equivalent entry in Discogs.
	Discogs_Series_URL_Link LinkType = 747
	// This links a recording to a page where it can be legally downloaded for
	// free.
	DownloadForFree_Recording_URL_Link LinkType = 255
	// This links a release to a page where it can be legally downloaded for free.
	DownloadForFree_Release_URL_Link LinkType = 75
	// This links an edit to its original recording. An "edit", for this
	// relationship, can be a radio edit (which involves streamlining a longer
	// track to around the 3 minute mark in order to make it suitable for radio
	// play), or a shortened, censored, or otherwise edited version of the same
	// material. The person who edited the recording can be linked using the <a
	// href="/relationship/40dff87a-e475-4aa6-b615-9935b564d756">editor
	// relationship type</a>.
	Edit_Recording_Recording_Link LinkType = 309
	// Links a recording to the place it was edited at.
	EditedAt_Place_Recording_Link LinkType = 819
	// Links a release to the place it was edited at.
	EditedAt_Place_Release_Link LinkType = 820
	// Links a recording to the area it was edited in. Use only when the place is
	// unknown!
	EditedIn_Area_Recording_Link LinkType = 821
	// Links a release to the area it was edited in. Use only when the place is
	// unknown!
	EditedIn_Area_Release_Link LinkType = 822
	// This describes an engineer responsible for either connecting disparate
	// elements of the audio recording, or otherwise redistributing material
	// recorded in the sessions. This is usually secondary, or additional to the
	// work done by the mix engineer. It can also involve streamlining a longer
	// track to around the 3 minute mark in order to make it suitable for radio
	// play (a "radio edit").
	Editor_Artist_Recording_Link LinkType = 144
	// This describes an engineer responsible for either connecting disparate
	// elements of the audio recording, or otherwise redistributing material
	// recorded in the sessions. This is usually secondary, or additional to the
	// work done by the mix engineer. It can also involve streamlining a longer
	// track to around the 3 minute mark in order to make it suitable for radio
	// play (a "radio edit").
	Editor_Artist_Release_Link LinkType = 38
	// This indicates that an artist was officially employed by a label as an
	// engineer.
	EngineerPosition_Artist_Label_Link LinkType = 120
	// Describes the fact a person was contracted by a place as an engineer.
	EngineerPosition_Artist_Place_Link LinkType = 701
	// This describes an engineer who performed a general engineering role.
	Engineer_Artist_Recording_Link LinkType = 138
	// This describes an engineer who performed a general engineering role.
	Engineer_Artist_Release_Link LinkType = 28
	// Links a recording to the place it was engineered at.
	EngineeredAt_Place_Recording_Link LinkType = 813
	// Links a release to the place it was engineered at.
	EngineeredAt_Place_Release_Link LinkType = 812
	// Links a recording to the area it was engineered in. Use only when the place
	// is unknown!
	EngineeredIn_Area_Recording_Link LinkType = 814
	// Links a release to the area it was engineered in. Use only when the place is
	// unknown!
	EngineeredIn_Area_Release_Link LinkType = 815
	// This links an artist to a fan-created website.
	Fanpage_Artist_URL_Link LinkType = 172
	// This links a label to a fan-created website.
	Fanpage_Label_URL_Link LinkType = 214
	// This relationship type is <strong>deprecated</strong>! If two recordings are
	// identical, please merge them.
	FirstTrackRelease_Recording_Recording_Link LinkType = 238
	// This relationship type can be used to link a place (generally a studio or
	// venue) to the person(s) who founded it.
	Founder_Artist_Place_Link LinkType = 832
	// This relationship type links genres to the areas they originate from.
	GenreOrigin_Area_Genre_Link LinkType = 1088
	// Points to the Geonames page for this area.
	Geonames_Area_URL_Link         LinkType = 713
	GetTheMusic_Artist_URL_Link    LinkType = 187
	GetTheMusic_Genre_URL_Link     LinkType = 1091
	GetTheMusic_Recording_URL_Link LinkType = 257
	GetTheMusic_Release_URL_Link   LinkType = 73
	// This credits the people or agency who did the graphic design, arranging
	// pieces of content into a coherent and aesthetically-pleasing sleeve design.
	GraphicDesign_Artist_Recording_Link LinkType = 125
	// This credits the people or agency who did the graphic design, arranging
	// pieces of content into a coherent and aesthetically-pleasing sleeve design.
	GraphicDesign_Artist_Release_Link LinkType = 27
	// This relationship is used to link a catalogue work series to a person whose
	// work it catalogues.
	HasCatalogue_Artist_Series_Link LinkType = 750
	// Links an event to the place where it was held.
	HeldAt_Event_Place_Link LinkType = 794
	// Links an event to the area where it was held. Use only if the exact place is
	// unknown.
	HeldIn_Area_Event_Link LinkType = 793
	// Links an event to its host/MC. Event hosts usually do introductions to the
	// show or each song.
	Host_Artist_Event_Link LinkType = 801
	// This links an artist to its page in <a
	// href="https://www.imdb.com/">IMDb</a>.
	IMDB_Artist_URL_Link LinkType = 178
	// This links a label to its page in <a href="https://www.imdb.com/">IMDb</a>.
	IMDB_Label_URL_Link LinkType = 313
	// Points to the Internet Movie Database page for this place.
	IMDB_Place_URL_Link LinkType = 706
	// This links a soundtrack release to the <a
	// href="https://www.imdb.com/">IMDb</a> page for the movie, show or game of
	// which it is a soundtrack.
	IMDB_ReleaseGroup_URL_Link LinkType = 97
	// This links a soundtrack work to the <a href="https://www.imdb.com/">IMDb</a>
	// page for the movie, show or game of which it is a soundtrack.
	IMDB_URL_Work_Link LinkType = 843
	// This links an artist to its page in <a
	// href="http://www.imslp.org/">IMSLP</a>.
	IMSLP_Artist_URL_Link LinkType = 754
	// Indicates a pictorial image (JPEG, GIF, PNG) of an artist.
	Image_Artist_URL_Link LinkType = 173
	// image
	Image_Instrument_URL_Link LinkType = 732
	// Indicates a pictorial image (JPEG, GIF, PNG) of a place
	Image_Place_URL_Link LinkType = 396
	// This indicates that a record label (company) owns or has the right to use an
	// imprint.
	Imprint_Label_Label_Link LinkType = 725
	// information page
	InformationPage_Instrument_URL_Link LinkType = 734
	// This relationship type links instruments to the areas they originate from.
	InstrumentOrigin_Area_Instrument_Link LinkType = 752
	// Indicates an artist that performed one or more instruments on this
	// recording.
	Instrument_Artist_Recording_Link LinkType = 148
	// Indicates an artist that performed one or more instruments on this release.
	Instrument_Artist_Release_Link LinkType = 44
	// Indicates a musician doing long-time instrumental support for another one on
	// albums and/or at concerts. This is a person-to-artist relationship that
	// normally applies to well-known solo artists, although it can sometimes apply
	// to groups.
	InstrumentalSupportingMusician_Artist_Artist_Link LinkType = 105
	// This links an artist to an URL containing an interview with that artist.
	Interview_Artist_URL_Link LinkType = 707
	// Indicates that two persons were romantically involved with each other
	// without being married.
	InvolvedWith_Artist_Artist_Link LinkType = 112
	// This relationship type can be used to link a label to the person(s) who
	// founded it.
	LabelFounder_Artist_Label_Link LinkType = 116
	// This describes a situation where one label is (or was) a subsidiary of
	// another label, during a given period of time. This should be used either to
	// describe the fact a label is a subdivision of another one, or, through
	// corporate acquisition of the former label, has become a subdivision of
	// another one.
	LabelOwnership_Label_Label_Link LinkType = 200
	// This relationship type links an artist to its corresponding page at Last.fm
	Lastfm_Artist_URL_Link LinkType = 840
	// This relationship type links an event to its corresponding page at Last.fm
	Lastfm_Event_URL_Link LinkType = 839
	// This relationship type links a label to its corresponding page at Last.fm
	Lastfm_Label_URL_Link LinkType = 838
	// This relationship type links a place to its corresponding page at Last.fm
	Lastfm_Place_URL_Link LinkType = 837
	// Links a release group with a launch event for it.
	LaunchEvent_Event_ReleaseGroup_Link LinkType = 797
	// Links a release with a launch event for it.
	LaunchEvent_Event_Release_Link LinkType = 796
	// This indicates that a person or firm provided legal representation for the
	// recording.
	LegalRepresentation_Artist_Recording_Link LinkType = 142
	// This indicates that a person or firm provided legal representation for the
	// release.
	LegalRepresentation_Artist_Release_Link LinkType = 22
	// Indicates the librettist for this release.
	Librettist_Artist_Release_Link LinkType = 57
	// Indicates the librettist for this work.
	Librettist_Artist_Work_Link LinkType = 169
	// This links a recording to a license under which it is available.
	License_Recording_URL_Link LinkType = 302
	// This links a release to a license under which it is available.
	License_Release_URL_Link LinkType = 301
	// This relationship indicates the company that was the licensee of this
	// release (that is, received a license for it from other company).
	Licensee_Label_Release_Link LinkType = 833
	// This relationship indicates the company that was the licensor of this
	// release.
	Licensor_Label_Release_Link LinkType = 712
	// This credits the author of liner notes provided with the release (usually on
	// the sleeve). While most time liner notes are just personnel information and
	// production data, in some cases they consist of a blurb of text (article).
	// This relationship type should be used in this last case.
	LinerNotes_Artist_Release_Link LinkType = 24
	// This is used to indicate that a release group is a live performance of a
	// studio release group.
	LivePerformance_ReleaseGroup_ReleaseGroup_Link LinkType = 17
	// This is used to link a label to an image of its logo.
	Logo_Label_URL_Link LinkType = 213
	// Indicates the lyricist for this release.
	Lyricist_Artist_Release_Link LinkType = 56
	// Indicates the lyricist for this work.
	Lyricist_Artist_Work_Link LinkType = 165
	// This relationship describes a URL where lyrics for the artist can be found.
	// Only sites on the <a
	// href="/doc/Style/Relationships/URLs/Lyrics_whitelist">whitelist</a> are
	// permitted.
	Lyrics_Artist_URL_Link LinkType = 197
	// This relationship describes a URL where lyrics for the release group can be
	// found. Only sites on the <a
	// href="/doc/Style/Relationships/URLs/Lyrics_whitelist">whitelist</a> are
	// permitted.
	Lyrics_ReleaseGroup_URL_Link LinkType = 93
	// This relationship describes a URL where lyrics for the work can be found.
	// Only sites on the <a
	// href="/doc/Style/Relationships/URLs/Lyrics_whitelist">whitelist</a> are
	// permitted.
	Lyrics_URL_Work_Link LinkType = 271
	// Links an event to (one of) its main performer(s).
	MainPerformer_Artist_Event_Link LinkType = 798
	// Links a release to the area it was manufactured ("made") in.
	ManufacturedIn_Area_Release_Link LinkType = 835
	// This indicates the organization that markets a release. This is
	// <strong>not</strong> the same concept as the <a href="/doc/Label">record
	// label</a>.
	Marketed_Label_Release_Link LinkType = 848
	// This links artists who were married.
	Married_Artist_Artist_Link LinkType = 111
	// This is used to indicate that the recording is a <a
	// href="/doc/Mix_Terminology#mash-up">mash-up</a> of two (or more) other
	// recordings.
	MashesUp_Recording_Recording_Link LinkType = 232
	// This is used to indicate that the release group is a mash-up <a
	// href="/doc/Mix_Terminology#mash-up">mash-up</a> of two (or more) other
	// release groups.
	MashesUp_ReleaseGroup_ReleaseGroup_Link LinkType = 10
	// Links a release to the place it was mastered at.
	MasteredAt_Place_Release_Link LinkType = 697
	// Links a release to the area it was mastered in. Use only when the place is
	// unknown!
	MasteredIn_Area_Release_Link LinkType = 756
	// Describes the fact a person was contracted by a place as a mastering
	// engineer.
	MasteringEngineerPosition_Artist_Place_Link LinkType = 704
	// This relationship type is <strong>deprecated</strong>! Please add mastering
	// engineers at the release level.
	Mastering_Artist_Recording_Link LinkType = 136
	// Indicates the mastering engineer for this work.
	Mastering_Artist_Release_Link LinkType = 42
	// This is used to indicate that a work is a medley of several other songs.
	// This means that the original songs were rearranged to create a new work in
	// the form of a medley. See <a
	// href="/relationship/d3fd781c-5894-47e2-8c12-86cc0e2c8d08">arranger</a> for
	// crediting the person who arranges songs into a medley.
	Medley_Work_Work_Link LinkType = 239
	// This indicates a person is a member of a group.
	MemberOfBand_Artist_Artist_Link LinkType = 103
	// This indicates that the artist performed a role not covered by other
	// relationship types.
	Misc_Artist_Recording_Link LinkType = 129
	// This indicates that the artist performed a role not covered by other
	// relationship types.
	Misc_Artist_Release_Link LinkType = 25
	// Indicates a miscellaneous support role. This is usually stated in the liner
	// notes of an album.
	Misc_Artist_Work_Link LinkType = 162
	// This relationship type is <strong>deprecated</strong>.
	Misc_URL_Work_Link LinkType = 270
	// This links a <a href="/doc/Mix_Terminology#DJ_mix">DJ-mix</a> to the artist
	// who mixed it.
	MixDJ_Artist_Recording_Link LinkType = 155
	// This links a <a href="/doc/Mix_Terminology#DJ_mix">DJ-mix</a> to the artist
	// who mixed it.
	MixDJ_Artist_Release_Link LinkType = 43
	// This describes an engineer responsible for using a mixing console to mix a
	// recorded track into a single piece of music suitable for release. For
	// remixing, see <a
	// href="/relationship/7950be4d-13a3-48e7-906b-5af562e39544">remixer</a>.
	Mix_Artist_Recording_Link LinkType = 143
	// This describes an engineer responsible for using a mixing console to mix a
	// recorded track into a single piece of music suitable for release. For
	// remixing, see <a
	// href="/relationship/ac6a86db-f757-4815-a07e-744428d2382b">remixer</a>.
	Mix_Artist_Release_Link LinkType = 26
	// Links a recording to the place it was mixed at.
	MixedAt_Place_Recording_Link LinkType = 694
	// Links a release to the place it was mixed at.
	MixedAt_Place_Release_Link LinkType = 696
	// Links a recording to the area it was mixed in. Use only when the place is
	// unknown!
	MixedIn_Area_Recording_Link LinkType = 758
	// Links a release to the area it was mixed in. Use only when the place is
	// unknown!
	MixedIn_Area_Release_Link LinkType = 757
	// Describes the fact a person was contracted by a place as a mixing engineer.
	MixingEngineerPosition_Artist_Place_Link LinkType = 703
	// This is used to link a music video to the corresponding audio recording.
	MusicVideo_Recording_Recording_Link     LinkType = 857
	MusicalRelationships_Artist_Artist_Link LinkType = 106
	// This relationship type links an artist to their Myspace page.
	Myspace_Artist_URL_Link LinkType = 189
	// This relationship type links a label to its Myspace page.
	Myspace_Label_URL_Link LinkType = 215
	// This relationship type can be used to link a MusicBrainz place to the
	// equivalent entry in Myspace.
	Myspace_Place_URL_Link LinkType = 462
	// Indicates the official homepage for an artist.
	OfficialHomepage_Artist_URL_Link LinkType = 183
	// Indicates the official homepage for an event.
	OfficialHomepage_Event_URL_Link LinkType = 782
	// Indicates the official homepage for a place.
	OfficialHomepage_Place_URL_Link LinkType = 363
	// This relationship type is used to link a release group to an official
	// website created specifically for the release group.
	OfficialHomepage_ReleaseGroup_URL_Link LinkType = 287
	// Indicates the official homepage for a series.
	OfficialHomepage_Series_URL_Link LinkType = 745
	// Indicates the official homepage for a label.
	OfficialSite_Label_URL_Link LinkType = 219
	// This relationship type links an artist to their online community page(s). An
	// online community is a group where any member can comment and contribute
	// content. The artist may or may not be a member of the group. Examples
	// include forums, LiveJournal communities and groups on Facebook, Last.fm and
	// Flickr.
	OnlineCommunity_Artist_URL_Link LinkType = 185
	OnlineData_Artist_URL_Link      LinkType = 841
	OnlineData_Label_URL_Link       LinkType = 221
	OnlineData_Place_URL_Link       LinkType = 660
	// Links an event to an orchestra that performed in it.
	Orchestra_Artist_Event_Link LinkType = 807
	// This links two <a href="/doc/Work" title="Work">works</a> where one work is
	// an orchestration of the other.
	Orchestration_Work_Work_Link LinkType = 316
	// This indicates the person who orchestrated the recording. Orchestration is a
	// special type of arrangement. It means the adaptation of a composition for an
	// orchestra, done in a way that the musical substance remains essentially
	// unchanged. The orchestrator is also responsible for writing scores for an
	// orchestra, band, choral group, individual instrumentalist(s) or vocalist(s).
	// In practical terms it consists of deciding which instruments should play
	// which notes in a piece of music.
	Orchestrator_Artist_Recording_Link LinkType = 300
	// This indicates the person who orchestrated the release. Orchestration is a
	// special type of arrangement. It means the adaptation of a composition for an
	// orchestra, done in a way that the musical substance remains essentially
	// unchanged. The orchestrator is also responsible for writing scores for an
	// orchestra, band, choral group, individual instrumentalist(s) or vocalist(s).
	// In practical terms it consists of deciding which instruments should play
	// which notes in a piece of music.
	Orchestrator_Artist_Release_Link LinkType = 40
	// This indicates the person who orchestrated the work. Orchestration is a
	// special type of arrangement. It means the adaptation of a composition for an
	// orchestra, done in a way that the musical substance remains essentially
	// unchanged. The orchestrator is also responsible for writing scores for an
	// orchestra, band, choral group, individual instrumentalist(s) or vocalist(s).
	// In practical terms it consists of deciding which instruments should play
	// which notes in a piece of music.
	Orchestrator_Artist_Work_Link LinkType = 164
	// This relationship links an organist to the place(s) (most commonly religious
	// buildings) at which they are the resident organist.
	Organist_Artist_Place_Link LinkType = 856
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Area_URL_Link LinkType = 730
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Artist_URL_Link LinkType = 188
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Event_URL_Link LinkType = 803
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Genre_URL_Link      LinkType = 1086
	OtherDatabases_Instrument_URL_Link LinkType = 753
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Label_URL_Link LinkType = 222
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Place_URL_Link LinkType = 561
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Recording_URL_Link LinkType = 306
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_ReleaseGroup_URL_Link LinkType = 96
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Release_URL_Link LinkType = 82
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_Series_URL_Link LinkType = 746
	// This links an entity to the equivalent entry in another database. Please
	// respect the <a
	// href="/doc/Other_Databases_Relationship_Type/Whitelist">whitelist</a>.
	OtherDatabases_URL_Work_Link LinkType = 273
	// This links two versions of a <a href="/doc/Work" title="Work">work</a>.
	OtherVersion_Work_Work_Link LinkType = 241
	// Indicates a parent-child relationship.
	Parent_Artist_Artist_Link LinkType = 109
	// This relationship type is <strong>deprecated</strong>! Please enter a
	// release with multiple discs as a single release containing multiple discs.
	PartOfSet_Release_Release_Link LinkType = 1
	// Designates that one area is contained by another.
	PartOf_Area_Area_Link LinkType = 356
	// Indicates that the artist is part of a series.
	PartOf_Artist_Series_Link LinkType = 996
	// Indicates that the event is part of a series.
	PartOf_Event_Series_Link LinkType = 802
	// Indicates that the recording is part of a series.
	PartOf_Recording_Series_Link LinkType = 740
	// Indicates that the release group is part of a series.
	PartOf_ReleaseGroup_Series_Link LinkType = 742
	// Indicates that the release is part of a series.
	PartOf_Release_Series_Link LinkType = 741
	// Indicates that the work is part of a series.
	PartOf_Series_Work_Link LinkType = 743
	// This indicates that an event is made up of multiple parts (e.g. a festival
	// happening on multiple venues over the course of a few days).
	Parts_Event_Event_Link LinkType = 818
	// parts
	Parts_Instrument_Instrument_Link LinkType = 739
	// This indicates that a place is part of another place.
	Parts_Place_Place_Link LinkType = 717
	// This indicates that a work is made up of multiple parts (e.g. an orchestral
	// suite broken into movements)
	Parts_Work_Work_Link              LinkType = 281
	Performance_Artist_Recording_Link LinkType = 122
	Performance_Artist_Release_Link   LinkType = 34
	// This is used to link works to their recordings.
	Performance_Recording_Work_Link LinkType = 278
	// Indicates an artist that performed on this recording.
	Performer_Artist_Recording_Link LinkType = 156
	// Indicates an artist that performed on this release.
	Performer_Artist_Release_Link LinkType = 51
	// Indicates an orchestra that performed on this recording.
	PerformingOrchestra_Artist_Recording_Link LinkType = 150
	// Indicates an orchestra that performed on this release.
	PerformingOrchestra_Artist_Release_Link LinkType = 45
	// This indicates a personal production label for an artist. A personal label
	// is a small label (usually a subdivision of a larger one) that exclusively
	// handles releases by that artist.
	PersonalLabel_Artist_Label_Link LinkType = 723
	// This indicates a personal publishing label for an artist. A personal
	// publishing label is a small label (usually a subdivision of a larger one)
	// that exclusively handles the rights to works by that artist.
	PersonalPublisher_Artist_Label_Link     LinkType = 724
	PersonalRelationship_Artist_Artist_Link LinkType = 113
	// This relationship indicates the artist is the <a
	// href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
	// copyright</a> holder for this recording.
	PhonographicCopyright_Artist_Recording_Link LinkType = 869
	// This relationship indicates the artist is the <a
	// href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
	// copyright</a> holder for this release.
	PhonographicCopyright_Artist_Release_Link LinkType = 710
	// This relationship indicates the label is the <a
	// href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
	// copyright</a> holder for this recording.
	PhonographicCopyright_Label_Recording_Link LinkType = 867
	// This relationship indicates the label is the <a
	// href="//en.wikipedia.org/wiki/Sound_recording_copyright_symbol">phonographic
	// copyright</a> holder for this release.
	PhonographicCopyright_Label_Release_Link LinkType = 711
	// This credits a person or agency whose photographs are included as part of a
	// recording.
	Photography_Artist_Recording_Link LinkType = 123
	// This credits a person or agency whose photographs are included as part of a
	// release.
	Photography_Artist_Release_Link LinkType = 20
	// This relationship type links an event to a promotional poster for the event.
	Poster_Event_URL_Link LinkType = 808
	// Indicates the area where the work had its first performance
	Premiere_Area_Work_Link LinkType = 715
	// Indicates the event where the work had its first performance
	Premiere_Event_Work_Link LinkType = 845
	// Indicates the place where the work had its first performance
	Premiere_Place_Work_Link LinkType = 716
	// Indicates an artist (generally a composer) this work was previously
	// attributed to, but who is currently confirmed (or very strongly suspected)
	// not to be the real author.
	PreviousAttribution_Artist_Work_Link LinkType = 834
	// This is used to link an artist to its primary concert venue.
	PrimaryConcertVenue_Artist_Place_Link LinkType = 714
	// Links a release to the area it was printed in.
	PrintedIn_Area_Release_Link LinkType = 849
	// Links a recording to the place it was produced at.
	ProducedAt_Place_Recording_Link LinkType = 825
	// Links a release to the place it was produced at.
	ProducedAt_Place_Release_Link LinkType = 824
	// Links a recording to the area it was produced in. Use only when the place is
	// unknown!
	ProducedIn_Area_Recording_Link LinkType = 827
	// Links a release to the area it was produced in. Use only when the place is
	// unknown!
	ProducedIn_Area_Release_Link LinkType = 826
	// This indicates that an artist was officially employed by a label as a
	// producer.
	ProducerPosition_Artist_Label_Link LinkType = 117
	// This indicates an artist who is responsible for the creative and practical
	// day-to-day aspects involved with making a musical recording.
	Producer_Artist_Recording_Link LinkType = 141
	// This indicates an artist who is responsible for the creative and practical
	// day-to-day aspects involved with making a musical recording.
	Producer_Artist_Release_Link     LinkType = 30
	Production_Artist_Recording_Link LinkType = 160
	Production_Artist_Release_Link   LinkType = 59
	Production_Recording_URL_Link    LinkType = 256
	Production_Release_URL_Link      LinkType = 72
	// This indicates the organization that promotes (or contracts out promotion)
	// for a release. This is <strong>not</strong> the same concept as the <a
	// href="/doc/Label">record label</a>.
	Promoted_Label_Release_Link LinkType = 359
	// This indicates the organization which releases a release. This is
	// <strong>not</strong> the same concept as the <a href="/doc/Label">record
	// label</a>.
	Published_Label_Release_Link LinkType = 362
	// Indicates the publisher of this recording. This is <strong>not</strong> the
	// same concept as the <a href="/doc/Label">record label</a>.
	Publishing_Artist_Recording_Link LinkType = 127
	// Indicates the publisher of this release. This is <strong>not</strong> the
	// same concept as the <a href="/doc/Label">record label</a>.
	Publishing_Artist_Release_Link LinkType = 32
	// Indicates the publisher of this work. This is <strong>not</strong> the same
	// concept as the <a href="/doc/Label">record label</a>.
	Publishing_Artist_Work_Link LinkType = 161
	// This relationship is deprecated. To indicate work publishers, add label-work
	// relationships. To indicate (P) holders, use the phonographic copyright
	// relationship.
	Publishing_Label_Recording_Link LinkType = 206
	Publishing_Label_Release_Link   LinkType = 66
	// Indicates the publisher of this work. This is <strong>not</strong> the same
	// concept as the <a href="/doc/Label">record label</a>.
	Publishing_Label_Work_Link LinkType = 208
	// This is used to link to a page where the recording can be purchased for
	// download.
	PurchaseForDownload_Recording_URL_Link LinkType = 254
	// This is used to link to a page where the release can be purchased for
	// download.
	PurchaseForDownload_Release_URL_Link LinkType = 74
	// This relationship type is used to link to a page where the release can be
	// purchased for mail order.
	PurchaseForMailOrder_Release_URL_Link LinkType = 79
	// This links an artist to the equivalent entry at PureVolume.
	Purevolume_Artist_URL_Link LinkType = 174
	// Links a recording to the event it was recorded at.
	RecordedAt_Event_Recording_Link LinkType = 809
	// Links a release to the event it was recorded at.
	RecordedAt_Event_Release_Link LinkType = 810
	// Links a recording to the place it was recorded at.
	RecordedAt_Place_Recording_Link LinkType = 693
	// Links a release to the place it was recorded at.
	RecordedAt_Place_Release_Link LinkType = 695
	// Links a recording to the area it was recorded in. Use only when the place is
	// unknown!
	RecordedIn_Area_Recording_Link LinkType = 698
	// Links a release to the area it was recorded in. Use only when the place is
	// unknown!
	RecordedIn_Area_Release_Link LinkType = 699
	// This indicates that an artist had a recording contract with a label.
	RecordingContract_Artist_Label_Link LinkType = 121
	// Describes the fact a person was contracted by a place as a recording
	// engineer.
	RecordingEngineerPosition_Artist_Place_Link LinkType = 702
	// related to
	RelatedTo_Instrument_Instrument_Link LinkType = 738
	// This relationship type is <strong>deprecated</strong>! <a
	// href="/doc/Style/Recording#Recordings_with_Different_Mastering">Different
	// remasters should be merged.</a>
	Remaster_Recording_Recording_Link LinkType = 236
	// This links a <a href="/doc/Mix_Terminology#remix">remixed</a> recording to
	// the source recording.
	Remix_Recording_Recording_Link LinkType = 230
	// This links a <a href="/doc/Mix_Terminology#remix">remix</a> release group to
	// the source release group and is used to indicate that the release group
	// includes remixed versions of all (or most of) the tracks in the other
	// release group.
	Remix_ReleaseGroup_ReleaseGroup_Link LinkType = 9
	// Links a recording to the place it was remixed at.
	RemixedAt_Place_Recording_Link LinkType = 829
	// Links a release to the place it was remixed at.
	RemixedAt_Place_Release_Link LinkType = 828
	// Links a recording to the area it was remixed in. Use only when the place is
	// unknown!
	RemixedIn_Area_Recording_Link LinkType = 830
	// Links a release to the area it was remixed in. Use only when the place is
	// unknown!
	RemixedIn_Area_Release_Link LinkType = 831
	// This links a recording to the person who remixed it by taking one or more
	// other tracks, substantially altering them and mixing them together with
	// other material. Note that this includes the artist who created a mash-up or
	// used samples as well.
	Remixer_Artist_Recording_Link LinkType = 153
	// This links a release to the person who remixed it by taking one or more
	// other tracks, substantially altering them and mixing them together with
	// other material. Note that this includes the artist who created a mash-up or
	// used samples as well.
	Remixer_Artist_Release_Link                           LinkType = 47
	RemixesAndCompilations_Artist_Recording_Link          LinkType = 157
	RemixesAndCompilations_Artist_Release_Link            LinkType = 50
	RemixesAndCompilations_Recording_Recording_Link       LinkType = 234
	RemixesAndCompilations_ReleaseGroup_ReleaseGroup_Link LinkType = 13
	// This links a postponed event to the later rescheduled event.
	RescheduledAs_Event_Event_Link LinkType = 836
	// Indicates a webpage that reviews the event in question.
	Review_Event_URL_Link LinkType = 842
	// Indicates a webpage that reviews the release (group) in question.
	Review_ReleaseGroup_URL_Link LinkType = 94
	// Indicates that an artist revised a work. In most cases, this will be the
	// original composer revising the work at a later date.
	RevisedBy_Artist_Work_Link LinkType = 844
	// This links different revisions of the same <a href="/doc/Work"
	// title="Work">work</a>.
	RevisionOf_Work_Work_Link LinkType = 315
	// This indicates the rights society associated with a release. The rights
	// society is an organization which collects royalties on behalf of the
	// artists.
	RightsSociety_Label_Release_Link LinkType = 349
	// Indicates that the recording contains samples from material by the indicated
	// artist. Use this only if you really cannot figure out the particular
	// recording that has been sampled.
	SamplesFromArtist_Artist_Recording_Link LinkType = 154
	// Indicates that the release contains samples from material by the indicated
	// artist. Use this only if you really cannot figure out the particular
	// recording that has been sampled.
	SamplesFromArtist_Artist_Release_Link LinkType = 49
	// Indicates that the recording contains samples from another.
	SamplesMaterial_Recording_Recording_Link LinkType = 231
	// Indicates that the recording contains samples from this release.
	SamplesMaterial_Recording_Release_Link LinkType = 69
	// This describes a URL where a score / sheet music for the work can be found.
	Score_URL_Work_Link LinkType = 274
	// This is used to link an artist to its corresponding page in SecondHandSongs
	// database.
	Secondhandsongs_Artist_URL_Link LinkType = 307
	// This is used to link a release to its corresponding page in SecondHandSongs
	// database.
	Secondhandsongs_Release_URL_Link LinkType = 308
	// This is used to link a work to its corresponding page in SecondHandSongs
	// database.
	Secondhandsongs_URL_Work_Link LinkType = 280
	// This relationship type links an artist to its corresponding page at
	// setlist.fm
	Setlistfm_Artist_URL_Link LinkType = 816
	// This relationship type links an event to its corresponding page at
	// setlist.fm
	Setlistfm_Event_URL_Link LinkType = 811
	// This relationship type links a place to its corresponding page at setlist.fm
	Setlistfm_Place_URL_Link   LinkType = 817
	ShowNotes_Release_URL_Link LinkType = 729
	// This links two siblings (brothers or sisters).
	Sibling_Artist_Artist_Link LinkType = 110
	// This indicates that a single or EP release group includes at least one track
	// taken from an album release group. This allows a release group to be linked
	// to its associated singles and EPs.
	SingleFrom_ReleaseGroup_ReleaseGroup_Link LinkType = 11
	// A social network page is a page for a series on a <a
	// href="https://en.wikipedia.org/wiki/Social_networking_service">social
	// network</a> which only people involved with the series can post content to.
	// Examples include Facebook pages, and accounts on Twitter, Instagram and
	// Flickr.
	SocialNetwork_Series_URL_Link LinkType = 784
	// This links an entity to the appropriate listing in the Songfacts database, a
	// user contributed database concerned with the stories behind the songs.
	Songfacts_URL_Work_Link LinkType = 289
	// This relationship type links an artist to its corresponding page at
	// Songkick.
	Songkick_Artist_URL_Link LinkType = 785
	// This relationship type links an event to its corresponding page at Songkick.
	Songkick_Event_URL_Link LinkType = 786
	// This relationship type links a place to its corresponding page at Songkick.
	Songkick_Place_URL_Link LinkType = 787
	// This describes an engineer responsible for ensuring that the sounds that the
	// artists make reach the microphones sounding pleasant, without unwanted
	// resonance or noise. Sometimes known as acoustical engineering.
	Sound_Artist_Recording_Link LinkType = 133
	// This describes an engineer responsible for ensuring that the sounds that the
	// artists make reach the microphones sounding pleasant, without unwanted
	// resonance or noise. Sometimes known as acoustical engineering.
	Sound_Artist_Release_Link LinkType = 29
	// This links an artist to its profile at SoundCloud.
	Soundcloud_Artist_URL_Link LinkType = 291
	// This links a label to its profile at SoundCloud.
	Soundcloud_Label_URL_Link LinkType = 290
	// This links a series (most commonly, but not necessarily always, a music
	// festival) to its official page at SoundCloud.
	Soundcloud_Series_URL_Link LinkType = 870
	// This relationship type is used to link an artist to a site where music can
	// be legally streamed for free, e.g. Spotify.
	StreamingMusic_Artist_URL_Link LinkType = 194
	// This relationship type is used to link a track to a site where the track can
	// be legally streamed for free, such as Spotify for audio tracks or YouTube
	// for videos.
	StreamingMusic_Recording_URL_Link LinkType = 268
	// This relationship type is used to link a release to a site where the tracks
	// can be legally streamed for free, e.g. Spotify.
	StreamingMusic_Release_URL_Link LinkType = 85
	// This relationship type is used to link a release to a site where the tracks
	// can be legally streamed for a subscription fee, e.g. Tidal.
	StreamingPaid_Release_URL_Link LinkType = 980
	// This links a subgroup to the group from which it was created. This
	// relationship type is the functional equivalent of the <a
	// href="/relationship/5be4c609-9afa-4ea0-910b-12ffb71e3821">member of band
	// type</a> for group-group relationships.
	Subgroup_Artist_Artist_Link LinkType = 722
	// Links a series to another series that exists within it.
	Subseries_Series_Series_Link LinkType = 823
	// type of
	Subtype_Instrument_Instrument_Link LinkType = 736
	// Links an event to (one of) its support act(s).
	SupportAct_Artist_Event_Link LinkType = 799
	// Indicates an artist doing long-time instrumental or vocal support for
	// another one on albums and/or at concerts. This is a person-to-artist
	// relationship that normally applies to well-known solo artists, although it
	// can sometimes apply to groups.
	SupportingMusician_Artist_Artist_Link LinkType = 104
	// This relationship links a concert tour to the artist(s) the tour is by.
	Tour_Artist_Series_Link LinkType = 859
	// This indicates that one release is identical to another release, but that
	// the release title and track titles have been either translated (into another
	// language) or transliterated (into another script).
	TranslTracklisting_Release_Release_Link LinkType = 2
	// This relationship specifies that an artist is a <a
	// href="http://en.wikipedia.org/wiki/Tribute_act">tribute</a> to another
	// specific artist/band; that is, it primarily performs covers of that artist.
	// They may also be referred to as cover bands. Some tribute artists may name
	// themselves, dress, and/or act similarly to the artists they pay tribute to.
	Tribute_Artist_Artist_Link LinkType = 728
	// This links a release group to an artist, to indicate that it is a tribute
	// album. Tribute albums often have a title in the form "A Tribute to Artist",
	// and they consist of covers of songs by the target artist, played by other
	// (sometimes very unknown) bands, to honor the target artist. Often they are
	// various artist compilations, but a single artist can perform the entire
	// tribute album.
	Tribute_Artist_ReleaseGroup_Link LinkType = 65
	// This relationship type links an artist to its corresponding page at <a
	// href="http://vgmdb.net/">VGMdb</a>. VGMdb is a community project dedicated
	// to cataloguing the music of video games and anime.
	VGMdb_Artist_URL_Link LinkType = 191
	// This relationship type links an event to its corresponding page at <a
	// href="http://vgmdb.net/">VGMdb</a>. VGMdb is a community project dedicated
	// to cataloguing the music of video games and anime.
	VGMdb_Event_URL_Link LinkType = 788
	// This relationship type links a label to its corresponding page at <a
	// href="http://vgmdb.net/">VGMdb</a>. VGMdb is a community project dedicated
	// to cataloguing the music of video games and anime.
	VGMdb_Label_URL_Link LinkType = 210
	// This relationship type links a release to its corresponding page <a
	// href="http://vgmdb.net/">VGMdb</a>. VGMdb is a community project dedicated
	// to cataloguing the music of video games and anime.
	VGMdb_Release_URL_Link LinkType = 86
	// This points to the <a href="//viaf.org/">VIAF</a> page for this artist. VIAF
	// is an international project to make a common authority file available to
	// libraries across the world. An authority file is similar to an MBID for
	// libraries. (<a
	// href="//en.wikipedia.org/wiki/Virtual_International_Authority_File">more
	// information on Wikipedia</a>)
	VIAF_Artist_URL_Link LinkType = 310
	// This points to the <a href="//viaf.org/">VIAF</a> page for this label. VIAF
	// is an international project to make a common authority file available to
	// libraries across the world. An authority file is similar to an MBID for
	// libraries. (<a
	// href="//en.wikipedia.org/wiki/Virtual_International_Authority_File">more
	// information on Wikipedia</a>)
	VIAF_Label_URL_Link LinkType = 311
	// This links an artist to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	VideoChannel_Artist_URL_Link LinkType = 303
	// This links an event to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	VideoChannel_Event_URL_Link LinkType = 804
	// This links a label to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	VideoChannel_Label_URL_Link LinkType = 304
	// This links a place to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	VideoChannel_Place_URL_Link LinkType = 495
	// This links a series to a channel, playlist, or user page on a video sharing
	// site containing videos curated by it.
	VideoChannel_Series_URL_Link LinkType = 805
	// Indicates a musician doing long-time vocal support for another one on albums
	// and/or at concerts. This is a person-to-artist relationship that normally
	// applies to well-known solo artists, although it can sometimes apply to
	// groups.
	VocalSupportingMusician_Artist_Artist_Link LinkType = 107
	// Indicates an artist that performed vocals on this recording.
	Vocal_Artist_Recording_Link LinkType = 149
	// Indicates an artist that performed vocals on this release.
	Vocal_Artist_Release_Link LinkType = 60
	// This links an (fictional) artist to the person that voice acted it.
	VoiceActor_Artist_Artist_Link LinkType = 292
	// Points to the Wikidata page for this area.
	Wikidata_Area_URL_Link LinkType = 358
	// Points to the Wikidata page for this artist.
	Wikidata_Artist_URL_Link LinkType = 352
	// Points to the Wikidata page for this event.
	Wikidata_Event_URL_Link LinkType = 790
	// Points to the Wikidata page for this genre, and will be used to fetch
	// Wikipedia summaries
	Wikidata_Genre_URL_Link LinkType = 1087
	// wikidata
	Wikidata_Instrument_URL_Link LinkType = 733
	// Points to the Wikidata page for this label.
	Wikidata_Label_URL_Link LinkType = 354
	// Points to the Wikidata page for this place
	Wikidata_Place_URL_Link LinkType = 594
	// Points to the Wikidata page for this release group.
	Wikidata_ReleaseGroup_URL_Link LinkType = 353
	// Points to the Wikidata page for this series.
	Wikidata_Series_URL_Link LinkType = 749
	// Points to the Wikidata page for this work.
	Wikidata_URL_Work_Link LinkType = 351
	// Points to the Wikipedia page for this area.
	Wikipedia_Area_URL_Link LinkType = 355
	// Points to the Wikipedia page for this artist.
	Wikipedia_Artist_URL_Link LinkType = 179
	// Points to the Wikipedia page for this event.
	Wikipedia_Event_URL_Link LinkType = 789
	// wikipedia
	Wikipedia_Instrument_URL_Link LinkType = 731
	// This is used to link a label to its corresponding Wikipedia page.
	Wikipedia_Label_URL_Link LinkType = 216
	// Points to the Wikipedia page for this place
	Wikipedia_Place_URL_Link LinkType = 595
	// Points to the Wikipedia page for this album.
	Wikipedia_ReleaseGroup_URL_Link LinkType = 89
	// Points to the Wikipedia page for this series.
	Wikipedia_Series_URL_Link LinkType = 744
	// Points to the Wikipedia page for this work.
	Wikipedia_URL_Work_Link LinkType = 279
	// This relationship is used to link a release to the artist responsible for
	// writing the music and/or the words (lyrics, libretto, etc.), when no more
	// specific information is available. If possible, the more specific composer,
	// lyricist and/or librettist types should be used, rather than this
	// relationship type.
	Writer_Artist_Release_Link LinkType = 54
	// This relationship is used to link a work to the artist responsible for
	// writing the music and/or the words (lyrics, libretto, etc.), when no more
	// specific information is available. If possible, the more specific composer,
	// lyricist and/or librettist types should be used, rather than this
	// relationship type.
	Writer_Artist_Work_Link LinkType = 167
	// This links an artist to the equivalent entry at YouTube.
	YouTube_Artist_URL_Link LinkType = 193
	// This relationship type can be used to link an event to the equivalent entry
	// in YouTube. URLs should follow the format
	// http://www.youtube.com/user/&lt;username&gt;
	YouTube_Event_URL_Link LinkType = 791
	// This links a label to the equivalent entry at YouTube.
	YouTube_Label_URL_Link LinkType = 225
	// This relationship type can be used to link a place to the equivalent entry
	// in YouTube. URLs should follow the format
	// http://www.youtube.com/user/<username>
	YouTube_Place_URL_Link LinkType = 528
	// This relationship type can be used to link a series to the equivalent entry
	// in YouTube. URLs should follow the format
	// http://www.youtube.com/user/&lt;username&gt;
	YouTube_Series_URL_Link LinkType = 792
)
